homepage:
    pattern:  /
    defaults: { _controller: TopxiaWebBundle:K12Default:index }

first_password:
    pattern:  /first/password
    defaults: { _controller: TopxiaWebBundle:K12Default:password }

login:
    pattern:  /login
    defaults: { _controller: TopxiaWebBundle:K12Default:login }
