services:
    form.type.default_category:
        class: Topxia\WebBundle\Form\Common\DefaultCategoryType
        tags:
            - { name: form.type, alias: default_category }

    form.type.user_role:
        class: Topxia\WebBundle\Form\Common\UserRoleType
        tags:
            - { name: form.type, alias: user_role }

    form.type.tags:
        class: Topxia\WebBundle\Form\Common\TagsType
        tags:
            - { name: form.type, alias: tags }

    form.type.gender:
        class: Topxia\WebBundle\Form\Common\GenderType
        tags:
            - { name: form.type, alias: gender }

    form.type.location:
        class: Topxia\WebBundle\Form\Common\LocationType
        tags:
            - { name: form.type, alias: location }

    form.type.act_type:
        class: Topxia\WebBundle\Form\Common\ActTypeType
        tags:
            - { name: form.type, alias: act_type }

    form.type.city:
        class: Topxia\WebBundle\Form\Common\CityType
        tags:
            - { name: form.type, alias: city }

    topxia.data_dict.user_role:
        class: Topxia\WebBundle\DataDict\UserRoleDict

    topxia.data_dict.gender:
        class: Topxia\WebBundle\DataDict\GenderDict

    authentication_handler:
        class: 'Topxia\Service\Common\LoginListener'

    topxia.timemachine:
        class:			Topxia\Common\TimeMachine
        arguments:		['Asia/Shanghai']