member:
    pattern: /memberzone
    defaults: { _controller: MemberBundle:Member:index }

member_course_explore:
    pattern: /memberzone/level/{levelId}/course
    defaults: { _controller: MemberBundle:Member:course, levelId: 0 }

member_history:
    pattern: /memberzone/history
    defaults: { _controller: MemberBundle:Member:history }

member_buy:
    pattern: /member/buy
    defaults: { _controller: MemberBundle:MemberOrder:buy }

member_renew:
    pattern: /member/renew
    defaults: { _controller: MemberBundle:MemberOrder:renew }

member_upgrade:
    pattern: /member/upgrade
    defaults: { _controller: MemberBundle:MemberOrder:upgrade }

member_upgrade_amount:
    pattern: /member/upgrade/amount
    defaults: { _controller: MemberBundle:MemberOrder:upgradeAmount }

member_upgrade_pay:
    pattern: /member/upgrade/pay
    defaults: { _controller: MemberBundle:MemberOrder:upgradePay }

member_pay:
    pattern: /member/pay
    defaults: { _controller: MemberBundle:MemberOrder:pay }

member_pay_return:
    pattern: /member/pay_return/{name}
    defaults: { _controller: MemberBundle:MemberOrder:payReturn }

member_pay_notify:
    pattern: /member/pay_notify/{name}
    defaults: { _controller: MemberBundle:MemberOrder:payNotify }
