admin_member_create:
    pattern: /member/create
    defaults: { _controller: MemberBundle:MemberAdmin:create }

admin_member_cancel:
    pattern: /member/{userId}/cancel
    defaults: { _controller: MemberBundle:MemberAdmin:cancel }

admin_member:
    pattern: /member/{type}
    defaults: { _controller: MemberBundle:MemberAdmin:index, type: 'all' }

admin_member_update:
    pattern: /member/update
    defaults: { _controller: MemberBundle:MemberAdmin:update }

admin_member_bought_history:
    pattern: /member/bought/history
    defaults: { _controller: MemberBundle:MemberAdmin:boughtHistory}

admin_member_bought_list:
    pattern: /member/bought/list
    defaults: { _controller: MemberBundle:MemberAdmin:boughtList}

admin_member_edit:
    pattern: /member/{userId}/edit
    defaults: { _controller: MemberBundle:MemberAdmin:edit}

admin_member_create_nickname_check:
    pattern:  /member/create/nickname/check
    defaults: { _controller: MemberBundle:MemberAdmin:nicknameCheck }

admin_user_level:
    pattern: /memberlevel
    defaults: { _controller: MemberBundle:MemberlevelAdmin:index }

admin_user_level_create:
    pattern: /memberlevel/create
    defaults: { _controller: MemberBundle:MemberlevelAdmin:create }

admin_user_level_update:
    pattern: /memberlevel/{id}/update
    defaults: { _controller: MemberBundle:MemberlevelAdmin:update }

admin_user_level_delete:
    pattern: /memberlevel/{id}/delete
    defaults: { _controller: MemberBundle:MemberlevelAdmin:delete }
    methods: [POST]

admin_user_level_sort:
    pattern: /memberlevel/sort
    defaults: { _controller: MemberBundle:MemberlevelAdmin:sort }

admin_user_level_picture:
    pattern: /memberlevel/picture
    defaults: { _controller: MemberBundle:MemberlevelAdmin:picture }

admin_user_level_icon:
    pattern: /memberlevel/icon
    defaults: { _controller: MemberBundle:MemberlevelAdmin:icon }

admin_user_level_on:
    pattern: /memberlevel/{id}/on
    defaults: { _controller: MemberBundle:MemberlevelAdmin:on }

admin_user_level_off:
    pattern: /memberlevel/{id}/off
    defaults: { _controller: MemberBundle:MemberlevelAdmin:off }

admin_level_zone:
    pattern: /levelzone
    defaults: { _controller: MemberBundle:MemberlevelAdmin:zone }

