vip:
    pattern: /vip/
    defaults: { _controller: MemberBundle:Member:index }

vip_course_explore:
    pattern: /memberzone/level/{levelId}/course
    defaults: { _controller: MemberBundle:Member:course, levelId: 0 }

vip_history:
    pattern: /vip/history
    defaults: { _controller: MemberBundle:Member:history }

vip_buy:
    pattern: /vip/buy
    defaults: { _controller: MemberBundle:MemberOrder:buy }

vip_renew:
    pattern: /vip/renew
    defaults: { _controller: MemberBundle:MemberOrder:renew }

vip_upgrade:
    pattern: /vip/upgrade
    defaults: { _controller: MemberBundle:MemberOrder:upgrade }

vip_upgrade_amount:
    pattern: /vip/upgrade/amount
    defaults: { _controller: MemberBundle:MemberOrder:upgradeAmount }

vip_upgrade_pay:
    pattern: /vip/upgrade/pay
    defaults: { _controller: MemberBundle:MemberOrder:upgradePay }

vip_pay:
    pattern: /vip/pay
    defaults: { _controller: MemberBundle:MemberOrder:pay }

vip_pay_return:
    pattern: /vip/pay_return/{name}
    defaults: { _controller: MemberBundle:MemberOrder:payReturn }

vip_pay_notify:
    pattern: /vip/pay_notify/{name}
    defaults: { _controller: MemberBundle:MemberOrder:payNotify }
