admin_vip_create:
    pattern: /vip/create
    defaults: { _controller: MemberBundle:MemberAdmin:create }

admin_vip_order:
    pattern: /vip/order
    defaults: { _controller: MemberBundle:MemberAdmin:order }

admin_vip_cancel:
    pattern: /vip/user/{userId}/cancel
    defaults: { _controller: MemberBundle:MemberAdmin:cancel }

admin_vip_list:
    pattern: /vip/type/{type}
    defaults: { _controller: MemberBundle:MemberAdmin:index, type: 'all' }

admin_vip_update:
    pattern: /vip/update
    defaults: { _controller: MemberBundle:MemberAdmin:update }

admin_vip_bought_history:
    pattern: /vip/bought/history
    defaults: { _controller: MemberBundle:MemberAdmin:boughtHistory}

admin_vip_bought_list:
    pattern: /vip/bought/list
    defaults: { _controller: MemberBundle:MemberAdmin:boughtList}

admin_vip_edit:
    pattern: /vip/user/{userId}/edit
    defaults: { _controller: MemberBundle:MemberAdmin:edit}

admin_vip_create_nickname_check:
    pattern:  /vip/create/nickname/check
    defaults: { _controller: MemberBundle:MemberAdmin:nicknameCheck }

admin_vip_level:
    pattern: /vip/level
    defaults: { _controller: MemberBundle:MemberlevelAdmin:index }

admin_vip_level_create:
    pattern: /vip/level/create
    defaults: { _controller: MemberBundle:MemberlevelAdmin:create }

admin_vip_level_update:
    pattern: /vip/level/{id}/update
    defaults: { _controller: MemberBundle:MemberlevelAdmin:update }

admin_vip_level_delete:
    pattern: /vip/level/{id}/delete
    defaults: { _controller: MemberBundle:MemberlevelAdmin:delete }
    methods: [POST]

admin_vip_level_sort:
    pattern: /vip/level/sort
    defaults: { _controller: MemberBundle:MemberlevelAdmin:sort }

admin_vip_level_picture:
    pattern: /vip/level/picture
    defaults: { _controller: MemberBundle:MemberlevelAdmin:picture }

admin_vip_level_icon:
    pattern: /vip/level/icon
    defaults: { _controller: MemberBundle:MemberlevelAdmin:icon }

admin_vip_level_on:
    pattern: /vip/level/{id}/on
    defaults: { _controller: MemberBundle:MemberlevelAdmin:on }

admin_vip_level_off:
    pattern: /vip/level/{id}/off
    defaults: { _controller: MemberBundle:MemberlevelAdmin:off }

admin_level_setting:
    pattern: /vip/level/setting
    defaults: { _controller: MemberBundle:MemberlevelAdmin:zone }

