parameters:
#    member_member.example.class: Member\MemberBundle\Example

services:
#    member_member.example:
#        class: %member_member.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
