admin_periodic_course_add:
    name: 创建周期课程
    parent: admin_course_manage
    router_name: course_create
    router_params: {'flag': 'periodic'}
    group: 2
    blank: 1

admin_app_center_show:
    name: ES(慕课版)应用
    parent: admin_app
    router_name: admin_app_center
    router_params: { postStatus : all }

admin_operation_school:
    name: 学校管理
    parent: admin_operation
    router_name: admin_school

admin_operation_school_manage:
    name: 学校管理
    parent: admin_operation_school
    router_name: admin_school

admin_operation_school_create:
    name: 添加学校组织
    parent: admin_operation_school
    router_name: admin_school_create
    mode: modal
    group: 2