custom_admin_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CustomAdminBundle:Default:index }
admin_tag:
    pattern:  /tag
    defaults: { _controller: CustomAdminBundle:Tag:index }
admin_tag_create:
    pattern:  /tag/create
    defaults: { _controller: CustomAdminBundle:Tag:create }
admin_tag_update:
    pattern:  /tag/{id}/update
    defaults: { _controller: CustomAdminBundle:Tag:update }
admin_tag_avatar:
     pattern: /tag/{id}/avatar
     defaults: {_controller: CustomAdminBundle:Tag:avatar}
admin_tag_avatar_crop:
    pattern: /tag/{id}/avatar/crop
    defaults: {_controller: CustomAdminBundle:Tag:avatarCrop}
# admin_user_avatar:
#     pattern:  /user/{id}/avatar
#     defaults: { _controller: TopxiaAdminBundle:User:avatar }
admin_column:
    pattern:  /column
    defaults: { _controller: CustomAdminBundle:Column:index }

admin_column_create:
    pattern:  /column/create
    defaults: { _controller: CustomAdminBundle:Column:create }

admin_column_checkname:
    pattern:  /column/checkname
    defaults: { _controller: CustomAdminBundle:Column:checkName}

admin_column_update:
    pattern:  /column/{id}/update
    defaults: { _controller: CustomAdminBundle:Column:update }

admin_column_delete:
    pattern:  /column/{id}/delete
    defaults: { _controller: CustomAdminBundle:Column:delete }
    methods:  [POST]
admin_column_avatar:
     pattern: /column/{id}/avatar
     defaults: {_controller: CustomAdminBundle:Column:avatar}
admin_column_avatar_crop:
    pattern: /column/{id}/avatar/crop
    defaults: {_controller: CustomAdminBundle:Column:avatarCrop}
admin_setting_course_setting:
    pattern:  /setting/course-setting
    defaults: { _controller: CustomAdminBundle:Setting:courseSetting }
