admin_course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: CustomAdminBundle:RoundCourse:nextRound }

admin_course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: CustomAdminBundle:RoundCourse:rounding }