parameters:
#    custom_admin.example.class: Custom\AdminBundle\Example
    template_overwrite_map:
        OrgBundle : CustomAdminBundle

services:
#    custom_admin.example:
#        class: %custom_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]