stages:
  - test

variables:
  MYSQL_DATABASE: edusoho_test
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

before_script:
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters_test.yml"
  - mkdir web/files
  - mkdir app/data/private_files
  - touch app/config/routing_plugins.yml

Unit Test With PHP 5.3:
  stage: test
  image: codeages/ci-php:5.3-1
  services:
    - mysql:5.5
  script:
    - phpunit -c app/
  only:
    - tags
    - develop
    - master
    - trigger

# Unit Test With PHP 5.5:
#   stage: test
#   image: codeages/ci-php:5.5-1
#   services:
#     - mysql:5.5
#   script:
#     - phpunit -c app/

Unit Test With PHP 7.0:
  stage: test
  image: codeages/ci-php:7.0-4
  services:
    - mysql:5.5
  script:
    -  phpdbg -qrr /usr/bin/phpunit -c app/ --coverage-text --colors=never
  only:
    - tags
    - develop
    - master
    - trigger
    - /^feature\/.*$/
