image: codeages/php-testing:5.3

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: edusoho_test
  MYSQL_ALLOW_EMPTY_PASSWORD: yes

before_script:
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir web/files
  - touch app/config/routing_plugins.yml

unittest:5.3:
  script:
  - phpunit -c app/