5.5 with js-test-unit:
  stage: test
  image: codeages/ci-php:5.5-5
  services:
    - mysql:5.5
    - redis:latest
  script:
    - sudo apt-get install npm
    - sudo npm install npm@latest -g
    - sudo npm install -g n
    - sudo n stable
    - npm install
    - npm run test