image: codeages/php-testing:5.3

services:
  - mysql:5.5

variables:
  MYSQL_DATABASE: edusoho_test
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

before_script:
  - cp app/config/parameters_test.yml.gitlabci app/config/parameters_test.yml
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - mkdir web/files
  - mkdir app/data/private_files
  - touch app/config/routing_plugins.yml

unittest:5.3:
  script:
  - phpunit -c app/