stages:
  - automation
  - test

variables:
  MYSQL_DATABASE: edusoho_test
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cp app/config/parameters.yml.dist app/config/parameters_test.yml
  - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters_test.yml"
  - "sed -i 's/\\s*database_name.*/    database_name: edusoho_test/g' app/config/parameters_test.yml"
  - "echo '    redis_host: redis:6379' >> app/config/parameters_test.yml"
  - "echo '    redis_timeout: 1' >> app/config/parameters_test.yml"
  - "echo '    redis_reserved: null' >> app/config/parameters_test.yml"
  - "echo '    redis_retry_interval: 100' >> app/config/parameters_test.yml"
  - mkdir web/files
  - mkdir -p app/data/private_files
  - touch app/config/routing_plugins.yml

Unit Test With PHP 5.3:
  stage: test
  image: codeages/ci-php:5.3-2
  services:
    - mysql:5.5
  script:
    - bin/phpunit -c app/
  only:
    - tags
    - develop
    - master
    - trigger

Unit Test With PHP 5.3 And Redis:
  stage: test
  image: codeages/ci-php:5.3-2
  services:
    - mysql:5.5
    - redis:latest
  script:
    - bin/phpunit -c app/
  only:
    - tags
    - develop
    - master
    - trigger

Unit Test With PHP 5.5:
  stage: test
  image: codeages/ci-php:5.5-5
  services:
    - mysql:5.5
    - redis:latest
  script:
    - php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection  `git diff --name-only --diff-filter=ACMRTUXB HEAD~..HEAD`
    - bin/phpunit -c app/

Unit Test With PHP 7.0 For Non-Develop:
  stage: test
  image: codeages/ci-php:7.0-7
  services:
    - mysql:5.5
    - redis:latest
  script:
    - sed -i 's/memory_limit.*/memory_limit = 2048M/g' /etc/php/7.0/phpdbg/php.ini
    - phpdbg -qrr bin/phpunit -c app/
  only:
    - tags
    - master
    - release
    - trigger

Unit Test With PHP 7.0 For Develop:
  stage: test
  image: codeages/ci-php:7.0-7
  services:
    - mysql:5.5
    - redis:latest
  script:
    - sed -i 's/memory_limit.*/memory_limit = 2048M/g' /etc/php/7.0/phpdbg/php.ini
    - phpdbg -qrr bin/phpunit -c app/ --coverage-text --colors=never --coverage-clover reports/phpunit.coverage.xml --log-junit reports/phpunit.xm
    - echo "sonar.links.ci=$SONAR_LINKS_CI" >> sonar-project.properties
    - echo "sonar.links.issue=$SONAR_LINKS_ISSUE" >> sonar-project.properties
    - echo "sonar.host.url=$SONAR_HOST" >> /opt/sonar-scanner/conf/sonar-scanner.properties
    - echo "sonar.login=$SONAR_TOKEN" >> /opt/sonar-scanner/conf/sonar-scanner.properties
    - /opt/sonar-scanner/bin/sonar-scanner
  only:
    - develop

AT With Java And Selenium:
  stage: automation
  image: ruanwenqin/ci:php5.5-jdk8

  services:
    - mysql:5.7
    - selenium/standalone-chrome:latest
  script:
    # 修改配置文件
    - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters.yml"
    - "sed -i 's/\\s*database_name.*/    database_name: edusoho_test/g' app/config/parameters.yml"
    # 启动web服务
    - git clone -b develop --single-branch http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusohoplugin/vip.git           plugins/VipPlugin
    - git clone -b develop --single-branch http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusohoplugin/chargecoin.git    plugins/ChargeCoinPlugin
    - git clone -b develop --single-branch http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusohoplugin/coupon.git        plugins/CouponPlugin
    - git clone -b develop --single-branch http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusohoplugin/discount.git      plugins/DiscountPlugin
    - git clone -b develop --single-branch http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusohoplugin/moneycard.git     plugins/MoneyCardPlugin
    - git clone -b develop --single-branch http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusohoplugin/userimporter.git  plugins/UserImporterPlugin
    # 安装插件
    - git clone -b feature/remote-driver http://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_HOST}/edusoho/GUIAutomation2.git
    - cd GUIAutomation2
    - /opt/apache-maven-3.5.2/bin/mvn -B -Dmaven.repo.local=/cache/.m2 compile
    - /opt/apache-maven-3.5.2/bin/mvn -q -Dmaven.repo.local=/cache/.m2 exec:java -Dexec.mainClass="com.eduosho.InitEnv" -Dfile.encoding=UTF-8 -Duser.language=zh -Duser.country=CN -Dexec.args="mysql"
    - mysql -uroot --password edusoho_test -e "select * from user"
    - while true; do echo 'Hit CTRL+C'; sleep 1; done
    #- cd .. && app/console server:start && cd GUIAutomation2
    #- /opt/apache-maven-3.5.2/bin/mvn -B -Dmaven.repo.local=/cache/.m2 clean test -DseleniumBrowserType=chrome -DseleniumHubUrl="http://selenium__standalone-chrome:4444/wd/hub" -DisLocal=false
  only:
      - schedules
      - triggers
      - web
      - api

Api Test With 5.5:
  stage: test
  image: ruanwenqin/ci-php:5.5-7
  services:
    - mysql:5.5
    - redis:latest
  script:
    # 修改配置文件
    - "sed -i 's/\\s*database_host.*/    database_host: mysql/g' app/config/parameters.yml"
    - "sed -i 's/\\s*database_name.*/    database_name: edusoho_test/g' app/config/parameters.yml"

    # 安装codeception(因为版本问题，放到gitlab ci上运行时安装)
    - composer config repo.packagist composer https://packagist.phpcomposer.com
    - composer require "codeception/codeception:*" --ignore-platform-reqs

    # 启动web服务
    - app/console server:start

    # install plugin
#    - git clone -b develop --single-branch ${CI_BUILD_REPO/edusoho\/edusoho\.git/edusohoplugin\/vip\.git} plugins/VipPlugin
#    - git clone -b develop --single-branch ${CI_BUILD_REPO/edusoho\/edusoho\.git/edusohoplugin\/chargecoin\.git} plugins/ChargeCoinPlugin
#    - git clone -b develop --single-branch ${CI_BUILD_REPO/edusoho\/edusoho\.git/edusohoplugin\/coupon\.git} plugins/CouponPlugin
#    - git clone -b develop --single-branch ${CI_BUILD_REPO/edusoho\/edusoho\.git/edusohoplugin\/discount\.git} plugins/DiscountPlugin
#    - git clone -b develop --single-branch ${CI_BUILD_REPO/edusoho\/edusoho\.git/edusohoplugin\/moneycard\.git} plugins/MoneyCardPlugin

    # 执行codeception的A PI 单元测试
    - bin/codecept run api

    # 执行newman的 API 单元测试
    - cd tests/api/Newman && newman run collection.json  --iteration-data param.json  --environment environment.json