branches:
  - master
  - feature/x8

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - SYMFONY_VERSION="~2.8.12" DB=mysql

git:
    submodules: false

before_install:
  - echo -e "Host gitlab.howzhi.net:4422\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git submodule update --init --recursive

before_script:
  - mysql -e 'CREATE DATABASE `edusoho-test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - mysql -e "GRANT ALL PRIVILEGES ON edusoho-test.* TO 'tester'@'localhost' IDENTIFIED BY 'tester'"
  - mysql -e "FLUSH PRIVILEGES"
  - cp app/config/config_test.yml.dist app/config/config_test.yml

script:
  - phpunit -c app/

cache:
  directories:
    - $HOME/.composer/cache