services:
    topxia.twig.permission_extension:
        class: Permission\PermissionBundle\TwigExtension\PermissionExtension
        arguments:    ['@service_container']
        tags:
            - { name: twig.extension }

    kernel.controller.permission_listener:
        class: Permission\Listener\KernelControllerListener
        arguments:    [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority:255 }
