mapi_mobile_api:
    pattern:  /{service}/{method}
    defaults: { _controller: TopxiaMobileBundleV2:MobileApi:index }
    methods: [GET, POST]

mapi_order_submit_pay_request:
    pattern:  /order/{id}/submit_pay_request
    defaults: { _controller: TopxiaMobileBundle:MobileOrder:submitPayRequest }


topxia_mobile_alipay_notify:
    pattern:  /{name}/alipay_notify
    defaults: { _controller: TopxiaMobileBundle:MobileAlipay:payNotify }

topxia_mobile_alipay_pay:
    pattern:  /alipay_pay
    defaults: { _controller: TopxiaMobileBundle:MobileAlipay:pay }

topxia_mobile_alipay_callback:
    pattern:  /{name}/alipay_callback
    defaults: { _controller: TopxiaMobileBundle:MobileAlipay:payCallBack }
