admin:
	name: 后台
	type: menu
	parent: null
admin_user:
	name: 用户
	type: menu
	parent: admin
admin_user_show:
	name: 用户管理
	type: menu
	parent: admin_user
admin_user_manage_son:
	name: 用户管理
	type: button
	parent: admin_user_show
admin_user_login_record:
	name: 登陆日志
	type: button
	parent: admin_user_show
admin_user_create:
	name: 添加新用户
	type: button
	parent: admin_user_manage_son
admin_user_details:
	name: 查看
	type: button
	parent: admin_user_manage_son
admin_user_edit:
	name: 编辑用户信息
	type: button
	parent: admin_user_manage_son
admin_user_set_roles:
	name: 设置用户组
	type: button
	parent: admin_user_manage_son
admin_user_change_avatar:
	name: 修改用户组
	type: button
	parent: admin_user_manage_son
admin_user_change_password:
	name: 修改密码
	type: button
	parent: admin_user_manage_son
admin_user_send_passwordreset_email:
	name: 发送密码重置邮件
	type: button
	parent: admin_user_manage_son
admin_user_send_emailverify_email:
	name: 发送Email验证邮件
	type: button
	parent: admin_user_manage_son
admin_user_lock:
	name: 封禁用户
	type: button
	parent: admin_user_manage_son
admin_user_login_record_details:
	name: 查看
	type: button
	parent: admin_user_login_record