admin:
    pattern:  /
    defaults: { _controller: TopxiaAdminBundle:Default:index }

admin_user:
    pattern:  /user
    defaults: { _controller: TopxiaAdminBundle:User:index }

admin_user_create:
    pattern:  /user/create
    defaults: { _controller: TopxiaAdminBundle:User:create }

admin_user_create_email_check:
    pattern:  /user/create/email/check
    defaults: { _controller: TopxiaAdminBundle:User:emailCheck }

admin_user_create_mobile_check:
    pattern:  /user/create/mobile/check
    defaults: { _controller: TopxiaAdminBundle:User:mobileCheck }

admin_user_create_email_or_mobile_check:
    pattern:  /user/create/email_or_mobile/check
    defaults: { _controller: TopxiaAdminBundle:User:emailOrMobileCheck }

admin_user_create_nickname_check:
    pattern:  /user/create/nickname/check
    defaults: { _controller: TopxiaAdminBundle:User:nicknameCheck }

admin_user_show:
    pattern:  /user/{id}
    defaults: { _controller: TopxiaAdminBundle:User:show }

admin_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: TopxiaAdminBundle:User:edit }

admin_user_lock:
    pattern:  /user/{id}/lock
    defaults: { _controller: TopxiaAdminBundle:User:lock }
    methods:  [POST]

admin_user_unlock:
    pattern:  /user/{id}/unlock
    defaults: { _controller: TopxiaAdminBundle:User:unlock }
    methods:  [POST]

admin_user_roles:
    pattern:  /user/{id}/roles
    defaults: { _controller: TopxiaAdminBundle:User:roles }

admin_user_avatar:
    pattern:  /user/{id}/avatar
    defaults: { _controller: TopxiaAdminBundle:User:avatar }

admin_user_avatar_crop:
    pattern:  /user/{id}/avatar/crop
    defaults: { _controller: TopxiaAdminBundle:User:avatarCrop }

admin_teacher:
    pattern:  /teacher
    defaults: { _controller: TopxiaAdminBundle:Teacher:index }

admin_teacher_promote:
    pattern:  /teacher/{id}/promote
    defaults: { _controller: TopxiaAdminBundle:Teacher:promote }
    methods:  [POST]

admin_teacher_promote_cancel:
    pattern:  /teacher/{id}/promote/cancel
    defaults: { _controller: TopxiaAdminBundle:Teacher:promoteCancel }
    methods:  [POST]

admin_user_change_password:
    pattern:  /user/{userId}/change/password
    defaults: { _controller: TopxiaAdminBundle:User:changePassword }

admin_user_send_passwordreset_email:
    pattern:  /user/{id}/send_passwordreset_email
    defaults: { _controller: TopxiaAdminBundle:User:sendPasswordResetEmail }
    methods:  [POST]

admin_user_send_emailverify_email:
    pattern:  /user/{id}/send_emailverify_email
    defaults: { _controller: TopxiaAdminBundle:User:sendEmailVerifyEmail }
    methods:  [POST]

admin_login_record:
    pattern: /login_record
    defaults: { _controller: TopxiaAdminBundle:LoginRecord:index }

admin_login_record_details:
    pattern: /login_record/{id}/details
    defaults: { _controller: TopxiaAdminBundle:LoginRecord:showUserLoginRecord }
