parameters:
    topxia_services:
        'Course.CourseService' : 'Custom\Service\Course\Impl\CourseServiceImpl'
        'User.UserService' : 'Custom\Service\User\Impl\UserServiceImpl'
        'User.AuthService' : 'Custom\Service\User\Impl\AuthServiceImpl'
        'Classroom:Classroom.ClassroomService' : 'Custom\Service\Classroom\Impl\ClassroomServiceImpl'
    topxia_daos:
        'Course.CourseDao' : 'Custom\Service\Course\Dao\Impl\CourseDaoImpl'
        'User.UserDao' : 'Custom\Service\User\Dao\Impl\UserDaoImpl'
        'Course.CourseMemberDao' : 'Custom\Service\Course\Dao\Impl\CourseMemberDaoImpl'