parameters:
    topxia_services:
        'Homework.HomeworkService' : 'Custom\Serivce\Homework\Impl\HomeworkServiceImpl'
        'Course.CourseService' : 'Custom\Service\Course\Impl\CourseServiceImpl'

    topxia_daos:
        'Course.CourseDao' : 'Custom\Service\Course\Dao\Impl\CourseDaoImpl'