parameters:
    topxia_services:
        'Crm.VipLevelService' : 'CRM\DataProvider\VipLevel\Service\Impl\VipLevelServiceImpl'

    topxia_daos:
        'Crm.VipLevelDao' :  'CRM\DataProvider\VipLevel\Service\Dao\Impl\VipLevelDaoImpl'
