parameters:
    topxia_services:
        'Course.CourseService' : 'Mooc\Service\Course\Impl\CourseServiceImpl'
        'Course.CourseCopyService' : 'Mooc\Service\Course\Impl\CourseCopyServiceImpl'
        'Course.CourseDeleteService' : 'Mooc\Service\Course\Impl\CourseDeleteServiceImpl'
        'User.UserService' : 'Mooc\Service\User\Impl\UserServiceImpl'
        'User.AuthService' : 'Mooc\Service\User\Impl\AuthServiceImpl'
        'Classroom:Classroom.ClassroomService' : 'Mooc\Service\Classroom\Impl\ClassroomServiceImpl'
        'Crontab.CrontabService' : 'Mooc\Service\CrontabJob\Impl\CrontabJobServiceImpl'
        'Testpaper.TestpaperService' : 'Mooc\Service\Testpaper\Impl\TestpaperServiceImpl'
        'Course.ThreadService' : 'Mooc\Service\Course\Impl\ThreadServiceImpl'
        'Theme.ThemeService' : 'Mooc\Service\Theme\Impl\ThemeServiceImpl'

    topxia_daos:
        'Course.CourseDao' : 'Mooc\Service\Course\Dao\Impl\CourseDaoImpl'
        'User.UserDao' : 'Mooc\Service\User\Dao\Impl\UserDaoImpl'
        'Course.CourseMemberDao' : 'Mooc\Service\Course\Dao\Impl\CourseMemberDaoImpl'
        'Classroom:Classroom.ClassroomMemberDao' : 'Mooc\Service\Classroom\Dao\Impl\ClassroomMemberDaoImpl'
        'Crontab.JobDao' : 'Mooc\Service\CrontabJob\Dao\Impl\CrontabJobDaoImpl'
        'Testpaper.TestpaperResultDao' : 'Mooc\Service\Testpaper\Dao\Impl\TestpaperResultDaoImpl'
        'Course.ThreadPostDao' : 'Mooc\Service\Course\Dao\Impl\ThreadPostDaoImpl'
        'Course.ThreadDao' : 'Mooc\Service\Course\Dao\Impl\ThreadDaoImpl'
        'Testpaper.TestpaperItemResultDao' : 'Mooc\Service\Testpaper\Dao\Impl\TestpaperItemResultDaoImpl'

    template_overwrite_map: 
       TopxiaAdminBundle: MoocAdminBundle
       TopxiaWebBundle: MoocWebBundle
       ClassroomBundle: MoocWebBundle


