parameters:
#    custom_web.example.class: Custom\WebBundle\Example
    template_overwrite_map:
        TopxiaWebBundle : CustomWebBundle
        OrgBundle : CustomAdminBundle

    topxia_daos:
        'Course.CourseDao' : 'Custom\Service\Course\Dao\Impl\CourseDaoImpl'
