parameters:
    topxia_services:
        'Course.CourseService' : 'Custom\Service\Course\Impl\CourseServiceImpl'

    topxia_daos:
        'Course.CourseDao' : 'Custom\Service\Course\Dao\Impl\CourseDaoImpl'