# 请不要修改此文件的参数
parameters:
    disabled_features: []
    cloud_client:
        name: default
        arguments: 
            videoCommands:
                avthumb/flv/r/24/vb/256k/vcodec/libx264/ar/22050/ab/64k/acodec/libmp3lame : sd
                avthumb/flv/r/24/vb/512k/vcodec/libx264/ar/44100/ab/64k/acodec/libmp3lame : hd
                avthumb/flv/r/24/vb/1024k/vcodec/libx264/ar/44100/ab/64k/acodec/libmp3lame : shd
            audioCommands: []
