bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

topxia_mobile:
    resource: "@TopxiaMobileBundle/Resources/config/routing.yml"
    prefix:   /mapi_v1

topxia_mobile_v2:
    resource: "@TopxiaMobileBundleV2/Resources/config/routing.yml"
    prefix:   /mapi_v2


custom_web:
    resource: "@CustomWebBundle/Resources/config/custom_routing.yml"
    prefix:   /

custom_admin:
    resource: "@CustomAdminBundle/Resources/config/custom_admin_routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppBundle/Resources/config/routing_admin.yml"
    prefix:   /admin
_plugins:
   resource: routing_plugins.yml

# Internal routing configuration to handle ESI
# _internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal