tbazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

topxia_mobile_v2:
    resource: "@TopxiaMobileBundleV2/Resources/config/routing.yml"
    prefix:   /mapi_v2

custom:
    resource: "@CustomBundle/Resources/config/routing.yml"
    prefix:   /

custom_admin:
    resource: "@CustomBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

_plugins:
   resource: routing_plugins.yml


app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

# Internal routing configuration to handle ESI
# _internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal