course_create:
    pattern:  /mooc/course/create
    defaults: { _controller: MoocWebBundle:Course:create }

course_create_settings:
    pattern:  /mooc/course/create/settings
    defaults: { _controller: MoocWebBundle:Course:createSettings }

course_create_settings_avatar:
    pattern:  /mooc/course/create/settings/avatar
    defaults: { _controller: MoocWebBundle:Course:createSettingsAvatar }

course_create_settings_avatar_crop:
    pattern:  /mooc/course/create/settings/avatar/crop
    defaults: { _controller: MoocWebBundle:Course:createSettingsAvatarCrop }

course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: MoocWebBundle:Course:nextRound }

course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: MoocWebBundle:Course:rounding }

course_explore:
    pattern:  /mooc/course/explore/{category}
    defaults: { _controller: MoocWebBundle:Course:explore, category:'' }

classroom_courses_pick:
    pattern: /classroom/{classroomId}/course/pick
    defaults: { _controller: MoocWebBundle:Classroom\Course:pick }

classroom_course_search:
    pattern: /classroom/{classroomId}/course/search
    defaults: { _controller: MoocWebBundle:Classroom\Course:search }

classroom_manage_students:
    pattern: /classroom/{id}/manage/students
    defaults: { _controller: MoocWebBundle:Classroom\ClassroomManage:students }

classroom_manage_aduitor:
    pattern: /classroom/{id}/manage/aduitor
    defaults: { _controller: MoocWebBundle:Classroom\ClassroomManage:aduitor }

classroom_manage_student_export_csv:
    pattern:  /classroom/{id}/manage/student/export/{role}
    defaults: { _controller: MoocWebBundle:Classroom\ClassroomManage:exportCsv }


search:
    pattern:  /search
    defaults: { _controller: MoocWebBundle:Search:index }

homepage:
    pattern:  /
    defaults: { _controller: MoocWebBundle:Default:index }

homepage_recommend_courses:
    pattern:  /recommend-courses
    defaults: { _controller: MoocWebBundle:Default:recommedCourses}

register_staffNo_check:
    pattern:  /register/staff-no/check
    defaults: { _controller: MoocWebBundle:Register:checkStaffNo }

course_manage_students:
    pattern:  /course/{id}/manage/students
    defaults: { _controller: MoocWebBundle:CourseStudentManage:index }

course_manage_student_export_csv:
    pattern:  /course/{id}/manage/student/export
    defaults: { _controller: MoocWebBundle:CourseStudentManage:exportCsv }

my_grades:
    pattern:  /my/grades
    defaults: { _controller: MoocWebBundle:MyGrades:index }

my_grades_cards:
    pattern:  /my/{courseId}/grades/cards
    defaults: { _controller: MoocWebBundle:MyGrades:gradesCards }

mobile:
    pattern: /mobile/
    defaults: { _controller: MoocWebBundle:Mobile:index }

course_manage_student_score_import:
    pattern:  /course/{id}/manage/student/score/import
    defaults: { _controller: MoocWebBundle:CourseScoreBatch:import }

course_manage_student_score_to_base:
    pattern:  /course/{id}/manage/student/score/importing
    defaults: { _controller: MoocWebBundle:CourseScoreBatch:excelDataImport }

course_manage_student_score_export_csv:
    pattern:  /course/{id}/manage/student/score/export
    defaults: { _controller: MoocWebBundle:CourseScoreBatch:exportCsv }

course_manage_score:
    pattern: /course/{courseId}/manage/score/setting
    defaults: { _controller: MoocWebBundle:CourseScore:scoreSetting }

course_manage_score_published:
    pattern: /course/{courseId}/manage/score/published
    defaults: { _controller: MoocWebBundle:CourseScore:scorePublished }

course_manage_transcripts:
    pattern: /course/{courseId}/manage/transcripts
    defaults: { _controller: MoocWebBundle:CourseScore:transcripts }

course_manage_transcripts_list:
    pattern: /course/{courseId}/manage/transcripts/list
    defaults: { _controller: MoocWebBundle:CourseScore:transcriptsList }

course_manage_student_score_edit:
    pattern: /course/{courseId}/manage/student/score/edit
    defaults: { _controller: MoocWebBundle:CourseScore:scoreEdit }

course_manage_student_grades_cards:
    pattern:  /course/{courseId}/student/{userId}/grades/cards
    defaults: { _controller: MoocWebBundle:CourseScore:studentGradesCards }

course_manage_lesson_create_testpaper:
    pattern:  /course/{id}/manage/lesson/create/testpaper
    defaults: { _controller: MoocWebBundle:CourseLessonManage:createTestpaper }

course_manage_lesson_edit_testpaper:
    pattern:  /course/{courseId}/manage/lesson/{lessonId}/edit/testpaper
    defaults: { _controller: MoocWebBundle:CourseLessonManage:editTestpaper }

course_lesson_do_test:
    pattern: /lesson/{lessonId}/test/{testId}/do
    defaults: { _controller: MoocWebBundle:CourseLesson:doTestpaper }

course_lesson_redo_test:
    pattern: /lesson/{lessonId}/test/{testId}/redo
    defaults: { _controller: MoocWebBundle:CourseLesson:reDoTestpaper }

course_manage_lesson_create:
    pattern:  /course/{id}/manage/lesson/create
    defaults: { _controller: MoocWebBundle:CourseLessonManage:create }

course_manage_lesson_edit:
    pattern:  /course/{courseId}/manage/lesson/{lessonId}/edit
    defaults: { _controller: MoocWebBundle:CourseLessonManage:edit }


