
admin_cloud_file_manage:
    name: 资源管理
    parent: admin_app
    children:
        admin_cloud_file:
            name: 云资源
            
# admin_material_lib_stats:
#     name: 数据统计
#     parent: admin_material_lib
