material_lib_browsing:
    pattern: /material/lib/browse/{type}/{viewMode}/{source}
    defaults: { _controller: MaterialLibBundle:MaterialLib:index, type: 'all', viewMode: 'thumb', source: 'upload'}

material_lib_my_sharing:
    pattern: /material/lib/my/sharing/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareForm }

material_lib_delete_file:
    pattern: /material/lib/{id}/delete
    defaults: { _controller: MaterialLibBundle:MaterialLib:delete }

material_lib_save_sharing:
    pattern: /material/lib/my/sharing/save
    defaults: { _controller: MaterialLibBundle:MaterialLib:saveShare }

material_lib_show_sharing_history:
    pattern: /material/lib/my/sharing/history
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareHistory }

material_lib_cancel_sharing:
    pattern: /material/lib/my/sharing/cancel
    defaults: { _controller: MaterialLibBundle:MaterialLib:cancelShare }

material_lib_my_sharing_contacts:
    pattern: /material/lib/recent/contacts
    defaults: { _controller: MaterialLibBundle:MaterialLib:findMySharingContacts }

material_lib_file_preview_content:
    pattern:  /materiallib/file/{fileId}/preview_content
    defaults: { _controller: TopxiaWebBundle:CourseLesson:file }

materiallib_file_deletes:
    pattern: /materiallib/file/deletes
    defaults: { _controller: MaterialLibBundle:MaterialLib:deletes }

material_lib_file_preview:
    pattern:  /material/lib/file/{fileId}/preview
    defaults: { _controller: MaterialLibBundle:MaterialLib:preview }

materiallib_file_delete:
    pattern: /materiallib/file/{id}/delete
    defaults: { _controller: MaterialLibBundle:MaterialLib:delete }

materiallib_file_download:
    pattern: /materiallib/file/{id}/download
    defaults: { _controller: MaterialLibBundle:MaterialLib:download }

material_lib_file_player:
    pattern:  /material/lib/{fileId}/player
    defaults: { _controller: MaterialLibBundle:MaterialLib:player }

material_lib_file_play_url:
    pattern:  /material/lib/{fileId}/play_url{suffix}
    defaults: { _controller: MaterialLibBundle:MaterialLib:playUrl, suffix:'' }
    requirements:
        suffix:  |.m3u8

material_lib_file_preview_hlskeyurl:
    pattern: /material/lib/{fileId}/preview/hlskeyurl/{token}
    defaults: { _controller: MaterialLibBundle:MaterialLib:hlskeyurl }

material_lib_file_preview_ppt:
    pattern: /material/lib/{fileId}/preview/ppt
    defaults: { _controller: MaterialLibBundle:MaterialLib:ppt }

material_lib_file_preview_content:
    pattern:  /material/lib/{fileId}/preview/content
    defaults: { _controller: MaterialLibBundle:MaterialLib:content }

global_file_player:
    pattern:  /global_file/{globalId}/player
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:player }

global_file_hls_playlist:
    pattern:  /global_file/{globalId}/playlist/{token}.m3u8
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:playlist }

global_file_hls_stream:
    pattern:  /global_file/{globalId}/stream/{level}/{token}.m3u8
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:stream }

global_file_hls_clef:
    pattern:  /global_file/{globalId}/clef/{token}
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:clef }

global_file_ppt:
    pattern:  /global_file/{globalId}/ppt
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:ppt }

global_file_document:
    pattern:  /global_file/{globalId}/document
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:document }

json_query_courses:
    pattern:  /json/courses
    defaults: { _controller: MaterialLibBundle:JSONAPI:courses }

json_query_users:
    pattern:  /json/users
    defaults: { _controller: MaterialLibBundle:JSONAPI:users }
