material_lib_browsing:
    pattern: /material/lib/browse/{type}/{viewMode}/{source}
    defaults: { _controller: MaterialLibBundle:MaterialLib:index, type: 'all', viewMode: 'thumb', source: 'upload'}
    
material_lib_delete_file:
    pattern: //material/lib/{id}/delete
    defaults: { _controller: MaterialLibBundle:MaterialLib:delete }
 
material_lib_my_sharing:
    pattern: /material/lib/my/sharing/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareForm }
    
material_lib_save_sharing:
    pattern: /material/lib/my/sharing/save
    defaults: { _controller: MaterialLibBundle:MaterialLib:saveShare }

material_lib_show_sharing_history:
    pattern: /material/lib/my/sharing/history
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareHistory }

material_lib_cancel_sharing:
    pattern: /material/lib/my/sharing/cancel
    defaults: { _controller: MaterialLibBundle:MaterialLib:cancelShare } 

material_lib_my_sharing_contacts:
    pattern: /material/lib/recent/contacts
    defaults: { _controller: MaterialLibBundle:MaterialLib:findMySharingContacts }  
    
material_lib_file_preview:
    pattern:  /material/lib/file/{fileId}/preview
    defaults: { _controller: MaterialLibBundle:MaterialLib:preview }

material_lib_file_preview_hlskeyurl:
    pattern: /material/lib/{fileId}/preview/hlskeyurl/{token}
    defaults: { _controller: MaterialLibBundle:MaterialLib:hlskeyurl }  

material_lib_file_preview_ppt:
    pattern: /material/lib/{fileId}/preview/ppt
    defaults: { _controller: MaterialLibBundle:MaterialLib:ppt }  
        
material_lib_file_preview_content:
    pattern:  /material/lib/{fileId}/preview/content
    defaults: { _controller: TopxiaWebBundle:CourseLesson:file }