material_lib_browsing:
    pattern: /material/lib/browse/{type}/{viewMode}/{source}
    defaults: { _controller: MaterialLibBundle:MaterialLib:index, type: 'all', viewMode: 'thumb', source: 'upload'}

material_lib_my_sharing:
    pattern: /material/lib/my/sharing/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareForm }

material_lib_save_sharing:
    pattern: /material/lib/my/sharing/save
    defaults: { _controller: MaterialLibBundle:MaterialLib:saveShare }

material_lib_show_sharing_history:
    pattern: /material/lib/my/sharing/history
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareHistory }

material_lib_cancel_sharing:
    pattern: /material/lib/my/sharing/cancel
    defaults: { _controller: MaterialLibBundle:MaterialLib:cancelShare }

material_lib_my_sharing_contacts:
    pattern: /material/lib/recent/contacts
    defaults: { _controller: MaterialLibBundle:MaterialLib:findMySharingContacts }

material_lib_file_preview_content:
    pattern:  /materiallib/file/{fileId}/preview_content
    defaults: { _controller: TopxiaWebBundle:CourseLesson:file }

materiallib_file_deletes:
    pattern: /materiallib/file/deletes
    defaults: { _controller: MaterialLibBundle:MaterialLib:deletes }

materiallib_file_preview:
    pattern:  /materiallib/file/{id}/preview
    defaults: { _controller: MaterialLibBundle:MaterialLib:preview }

materiallib_file_delete:
    pattern: /materiallib/file/{id}/delete
    defaults: { _controller: MaterialLibBundle:MaterialLib:delete }

materiallib_file_download:
    pattern: /materiallib/file/{id}/download
    defaults: { _controller: MaterialLibBundle:MaterialLib:download }