services:
    api_resource_kernel:
        class: ApiBundle\Api\ResourceKernel
        arguments: ['@service_container']

    api_exception_listener:
        class: ApiBundle\EventListener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1024 }