services:
    api_token_user_provider:
        class: ApiBundle\Security\TokenUserProvider
        arguments: ['@service_container']

    api_security_policy_manager:
          class:  ApiBundle\Security\SecurityPolicyManager
          arguments: ['@service_container']

    api_token_authenticator:
        class:  ApiBundle\Security\TokenAuthenticator
        arguments: ['@service_container', '@api_security_policy_manager']
        public: false

    api_exception_listener:
        class: ApiBundle\EventListener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1024 }