course_tasks:
  pattern:  /course/{courseId}/tasks
  defaults: { _controller: TaskBundle:TaskManage:tasks }

course_task_create:
  pattern:  /course/{courseId}/task
  defaults: { _controller: TaskBundle:TaskManage:create }

course_task_update:
  pattern:  /course/{courseId}/task/{id}/update
  defaults: { _controller: TaskBundle:TaskManage:update }

course_task_delete:
  pattern:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: TaskBundle:TaskManage:delete }

course_task_show:
  pattern:  /course/{courseId}/task/{id}/show
  defaults: { _controller: TaskBundle:Task:show }

course_task_activity_show:
  pattern:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: TaskBundle:Task:taskActivity }
