my_teaching_courses:
    pattern: /my/teaching/courses/{filter}
    defaults: { _controller: CustomWebBundle:MyTeaching:courses, filter:'normal' }

course_create:
    pattern:  /course/create
    defaults: { _controller: CustomWebBundle:Course:create }


course_show:
    pattern:  /course/{id}
    defaults: { _controller: CustomWebBundle:Course:show }

course_manage:
    pattern:  /course/{id}/manage
    defaults: { _controller: CustomWebBundle:CourseManage:index }

course_manage_base:
    pattern:  /course/{id}/manage/base
    defaults: { _controller: CustomWebBundle:CourseManage:base }

course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: CustomWebBundle:Course:nextRound }

course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: CustomWebBundle:Course:rounding }

