course_buy:
    pattern:  /course/{id}/buy
    defaults: { _controller: CustomWebBundle:CourseOrder1:buy }
course_order_pay:
    pattern:  /course/order/pay
    defaults: { _controller: CustomWebBundle:CourseOrder1:pay }
    methods: [POST]

coupon_check:
    pattern:  /{type}/{id}/coupon/check
    defaults: { _controller: CustomWebBundle:Order1:couponCheck }

course_order_pay_return:
    pattern:  /course/order/pay/{name}/return
    defaults: { _controller: CustomWebBundle:CourseOrder1:payReturn }

course_order_pay_notify:
    pattern:  /course/order/pay/{name}/notify
    defaults: { _controller: CustomWebBundle:CourseOrder1:payNotify }

course_order_repay:
    pattern:  /course/order/repay
    defaults: { _controller: CustomWebBundle:CourseOrder1:repay }
    methods: [POST]

group_show:
    pattern:  /group/{id}
    defaults: { _controller: CustomWebBundle:Group1:groupIndex }

group_sign:
    pattern:  /sign/{groupId}
    defaults: { _controller: CustomWebBundle:Sign:sign }

signed_records:
    pattern:  /sign/{groupId}/records
    defaults: { _controller: CustomWebBundle:Sign:getSignedRecordsByPeriod }

sign_repair:
    pattern:  /sign/{groupId}/repair
    defaults: { _controller: CustomWebBundle:Sign:signRepair }