homepage:
    pattern:  /
    defaults: { _controller: CustomWebBundle:Default:index }


settings:
    pattern:  /settings/
    defaults: { _controller: CustomWebBundle:Settings:profile }
    
teacher_tag_match:
    pattern: /teacher/tag/match_jsonp
    defaults: { _controller: CustomWebBundle:TagTeacher:match }
    


