course_create:
    pattern:  /custom/course/create
    defaults: { _controller: CustomWebBundle:Course:create }

course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: CustomWebBundle:Course:nextRound }

course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: CustomWebBundle:Course:rounding }

course_explore:
    pattern:  /mooc/course/explore/{category}
    defaults: { _controller: CustomWebBundle:Course:explore, category:'' }

classroom_courses_pick:
    pattern: /classroom/{classroomId}/course/pick
    defaults: { _controller: CustomWebBundle:Classroom\Course:pick }

classroom_course_search:
    pattern: /classroom/{classroomId}/course/search
    defaults: { _controller: CustomWebBundle:Classroom\Course:search }

classroom_manage_students:
    pattern: /classroom/{id}/manage/students
    defaults: { _controller: CustomWebBundle:Classroom\ClassroomManage:students }

classroom_manage_aduitor:
    pattern: /classroom/{id}/manage/aduitor
    defaults: { _controller: CustomWebBundle:Classroom\ClassroomManage:aduitor }

classroom_manage_student_export_csv:
    pattern:  /classroom/{id}/manage/student/export/{role}
    defaults: { _controller: CustomWebBundle:Classroom\ClassroomManage:exportCsv }


search:
    pattern:  /search
    defaults: { _controller: CustomWebBundle:Search:index }

homepage:
    pattern:  /
    defaults: { _controller: CustomWebBundle:Default:index }

homepage_recommend_courses:
    pattern:  /recommend-courses
    defaults: { _controller: CustomWebBundle:Default:recommedCourses}

register_staffNo_check:
    pattern:  /register/staff-no/check
    defaults: { _controller: CustomWebBundle:Register:checkStaffNo }

course_manage_students:
    pattern:  /course/{id}/manage/students
    defaults: { _controller: CustomWebBundle:CourseStudentManage:index }

course_manage_student_export_csv:
    pattern:  /course/{id}/manage/student/export
    defaults: { _controller: CustomWebBundle:CourseStudentManage:exportCsv }

my_grades:
    pattern:  /my/grades
    defaults: { _controller: CustomWebBundle:MyGrades:index }

my_grades_cards:
    pattern:  /my/{courseId}/grades/cards
    defaults: { _controller: CustomWebBundle:MyGrades:gradesCards }

mobile:
    pattern: /mobile/
    defaults: { _controller: CustomWebBundle:Mobile:index }

course_manage_student_score_import:
    pattern:  /course/{id}/manage/student/score/import
    defaults: { _controller: CustomWebBundle:CourseScoreBatch:import }

course_manage_student_score_to_base:
    pattern:  /course/{id}/manage/student/score/importing
    defaults: { _controller: CustomWebBundle:CourseScoreBatch:excelDataImport }

course_manage_student_score_export_csv:
    pattern:  /course/{id}/manage/student/score/export
    defaults: { _controller: CustomWebBundle:CourseScoreBatch:exportCsv }

course_manage_score:
    pattern: /course/{courseId}/manage/score/setting
    defaults: { _controller: CustomWebBundle:CourseScore:scoreSetting }

course_manage_score_published:
    pattern: /course/{courseId}/manage/score/published
    defaults: { _controller: CustomWebBundle:CourseScore:scorePublished }

course_manage_transcripts:
    pattern: /course/{courseId}/manage/transcripts
    defaults: { _controller: CustomWebBundle:CourseScore:transcripts }

course_manage_transcripts_list:
    pattern: /course/{courseId}/manage/transcripts/list
    defaults: { _controller: CustomWebBundle:CourseScore:transcriptsList }

course_manage_student_score_edit:
    pattern: /course/{courseId}/manage/student/score/edit
    defaults: { _controller: CustomWebBundle:CourseScore:scoreEdit }

course_manage_student_grades_cards:
    pattern:  /course/{courseId}/student/{userId}/grades/cards
    defaults: { _controller: CustomWebBundle:CourseScore:studentGradesCards }
