my_homework_list:
    pattern: /my/homework/list
    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:list }

course_manage_lesson_homework_create:
    pattern: /course/{courseId}/manage/lesson/{lessonId}/homework/create
    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:create }

#course_create:
#    pattern:  /course/create
#    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:test }
#
#course_show:
#    pattern:  /course/{id}
#    defaults: { _controller: TopxiaWebBundle:Course:show }