homepage:
    path:     /
    defaults: { _controller: CustomWebBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: CustomWebBundle:Login:index }

my_teaching_courses:
    pattern: /my/teaching/courses/{filter}
    defaults: { _controller: CustomWebBundle:MyTeaching:orgCourses, filter:'normal' }

course_manage_test_check:
    pattern: /course/check/{id}/{status}/list
    defaults: { _controller: CustomWebBundle:Testpaper:teacherCheckInCourse }

course_manage_list_teacher_test_reviewing:
    pattern: /my/teacher/reviewing/test/list
    defaults: { _controller: CustomWebBundle:Testpaper:listReviewingTest }

course_manage_list_teacher_test_finished:
    pattern: /my/teacher/finished/test/list
    defaults: { _controller: CustomWebBundle:Testpaper:listFinishedTest }