# homepage:
#     pattern:  /
#     defaults: { _controller: CustomWebBundle:Default:index }

course_show:
    pattern:  /course/{id}
    defaults: { _controller: CustomWebBundle:Course:show }

course_preview:
    pattern:  /course/{id}/preview
    defaults: { _controller: CustomWebBundle:Course:preview }

course_header:
    pattern:  /course/{id}/header
    defaults: { _controller: CustomWebBundle:Course:header }

course_relatedArticles:
    pattern:  /course/{id}/relatedArticles
    defaults: { _controller: CustomWebBundle:Course:relatedArticles }

course_manage_base:
    pattern:  /course/{id}/manage/base
    defaults: { _controller: CustomWebBundle:CourseManage:base }

course_manage:
    pattern:  /course/{id}/manage
    defaults: { _controller: CustomWebBundle:CourseManage:index }

course_manage_price:
    pattern:  /course/{id}/manage/price
    defaults: { _controller: CustomWebBundle:CourseManage:price }










course_threads:
    pattern:  /course/{id}/thread
    defaults: { _controller: CustomWebBundle:CourseThread:index }

course_thread_create:
    pattern:  /course/{id}/thread/create
    defaults: { _controller: CustomWebBundle:CourseThread:create }

course_thread_show:
    pattern:  /course/{courseId}/thread/{id}
    defaults: { _controller: CustomWebBundle:CourseThread:show }

course_thread_edit:
    pattern:  /course/{courseId}/thread/{id}/edit
    defaults: { _controller: CustomWebBundle:CourseThread:edit }

course_thread_delete:
    pattern:  /course/{courseId}/thread/{id}/delete
    defaults: { _controller: CustomWebBundle:CourseThread:delete }

course_thread_stick:
    pattern:  /course/{courseId}/thread/{id}/stick
    defaults: { _controller: CustomWebBundle:CourseThread:stick }

course_thread_unstick:
    pattern:  /course/{courseId}/thread/{id}/unstick
    defaults: { _controller: CustomWebBundle:CourseThread:unstick }

course_thread_elite:
    pattern:  /course/{courseId}/thread/{id}/elite
    defaults: { _controller: CustomWebBundle:CourseThread:elite }

course_thread_unelite:
    pattern:  /course/{courseId}/thread/{id}/unelite
    defaults: { _controller: CustomWebBundle:CourseThread:unelite }

course_thread_post_delete:
    pattern:  /course/{courseId}/thread/{threadId}/post/{id}/delete
    defaults: { _controller: CustomWebBundle:CourseThread:deletePost }

course_thread_post_edit:
    pattern:  /course/{courseId}/thread/{threadId}/post/{id}/edit
    defaults: { _controller: CustomWebBundle:CourseThread:editPost }
















course_review_list:
    pattern:  /course/{id}/review/list
    defaults: { _controller: CustomWebBundle:CourseReview:list }

course_review_create:
    pattern:  /course/{id}/review/create
    defaults: { _controller: CustomWebBundle:CourseReview:create }

course_review_post_create:
    pattern:  /course/{id}/review/post/create
    defaults: { _controller: CustomWebBundle:CourseReview:createPost }

course_review_post_delete:
    pattern:  /course/{courseId}/review/post/{postId}/delete
    defaults: { _controller: CustomWebBundle:CourseReview:deletePost }

course_review_post_edit:
    pattern:  /course/{courseId}/review/post/{postId}/edit
    defaults: { _controller: CustomWebBundle:CourseReview:editPost }





















# # course_favorite:
# #     pattern: /course/{id}/favorite
# #     defaults: { _controller: CustomWebBundle:Course:favorite }
# #     methods: [POST]

column_match:
    pattern: /column/match_jsonp
    defaults: { _controller: CustomWebBundle:Column:match }

# course_search_index:
#     pattern: /course/search/xxx
#     defaults: {_controller: CustomWebBundle:CourseSearch:index }

# # vip:
# #     pattern: /vip/
# #     defaults: { _controller: CustomWebBundle:Vip:index }

column_course_vote:
    pattern: /column/course/vote
    defaults: {_controller: CustomWebBundle:ColumnCourse:courseVote }

tag_course_list:
    pattern:  /tag/course/{tagId}/list
    defaults:  {_controller: CustomWebBundle:Tag:index ,tagId:'' }
tag_page:
    pattern:  /tag/page/{page}
    defaults:  {_controller: CustomWebBundle:Tag:page ,page:'' }
course_search_index:
    pattern:  /course/search/index
    defaults: {_controller: CustomWebBundle:CourseSearch:index }
column:
    pattern:  /column
    defaults: {_controller: CustomWebBundle:Column:index }
column_course:
    pattern:  /column/{id}/course
    defaults: {_controller: CustomWebBundle:ColumnCourse:index,id:'' }
vip_buy:
    pattern: /vip/buy
    defaults: { _controller: CustomWebBundle:VipOrder:buy }
index_tag_page:
    pattern:  /index/tag/page/{page}
    defaults:  {_controller: CustomWebBundle:Tag:indexPage ,page:'' }
ajax_page:
    pattern:  /index/tag/ajax/page/{page}
    defaults:  {_controller: CustomWebBundle:Tag:ajaxPage ,page:'' }




