my_teaching_courses:
    pattern: /my/teaching/courses/{filter}
    defaults: { _controller: CustomWebBundle:MyTeaching:courses, filter:'normal' }

course_create:
    pattern:  /course/create
    defaults: { _controller: CustomWebBundle:Course:create }

course_explore:
    pattern:  /course/explore/{category}
    defaults: { _controller: CustomWebBundle:Course:explore, category:'' }

course_show:
    pattern:  /course/{id}
    defaults: { _controller: CustomWebBundle:Course:show }

course_manage:
    pattern:  /course/{id}/manage
    defaults: { _controller: CustomWebBundle:CourseManage:index }

course_manage_base:
    pattern:  /course/{id}/manage/base
    defaults: { _controller: CustomWebBundle:CourseManage:base }

course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: CustomWebBundle:Course:nextRound }

course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: CustomWebBundle:Course:rounding }

course_manage_lesson:
    pattern:  /course/{id}/manage/lesson
    defaults: { _controller: CustomWebBundle:CourseLessonManage:index }

course_homework_submit:
    pattern: /course/{courseId}/homework/{homeworkId}/submit
    defaults: { _controller: CustomWebBundle:CourseHomework:submit }

course_homework_check_list:
    pattern: /course/{courseId}/check/homework/{status}/list
    defaults: { _controller: CustomWebBundle:CourseHomework:checkList }

my_teaching_homework_list:
    pattern: /my/teaching/homework/list
    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:teachingList }

my_homework_list:
    pattern: /my/homework/list
    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:list }

course_lesson_plugin_homework_list:
    pattern:  /lessonplugin/homework/list
    defaults: { _controller: CustomWebBundle:LessonHomeworkPlugin:list }

course_manage_lesson_homework_create:
    pattern: /course/{courseId}/manage/lesson/{lessonId}/homework/create
    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:create }

course_manage_lesson_homework_edit:
    pattern: /course/{courseId}/manage/lesson/{lessonId}/homework/{homeworkId}/edit
    defaults: { _controller: CustomWebBundle:CourseHomeworkManage:edit }

course_threads:
    pattern:  /course/{id}/thread/
    defaults: { _controller: CustomWebBundle:CourseThread:index }

course_materials:
    pattern:  /course/{id}/material/
    defaults: { _controller: CustomWebBundle:CourseMaterial:index }

course_homeworks:
    pattern:  /course/{id}/homeworks/
    defaults: { _controller: CustomWebBundle:Homework:index }

course_review_list:
    pattern:  /course/{id}/reviews/
    defaults: { _controller: CustomWebBundle:CourseReview:index }

course_notes:
    pattern:  /course/{courseId}/notes
    defaults: { _controller: CustomWebBundle:CourseNote:index }

course_info:
    pattern:  /course/{id}/info
    defaults: { _controller: CustomWebBundle:CourseInfo:index }

pair_review_create:
    pattern:  /homeworks/{homeworkId}/pair_reviews/create
    defaults: { _controller: CustomWebBundle:HomeworkPairReview:create }
