json_tags_search:
    pattern:  /json/tags/search
    defaults: { _controller: CustomWebBundle:JsonTags:search }

json_tags_match:
    pattern:  /json/tags/match
    defaults: { _controller: CustomWebBundle:JsonTags:match }

json_tags_query:
    pattern:  /json/tags/query
    defaults: { _controller: CustomWebBundle:JsonTags:query }

json_knowledges_search:
    pattern:  /json/Knowledges/search
    defaults: { _controller: CustomWebBundle:JsonKnowledges:search }

json_knowledges_match:
    pattern:  /json/Knowledges/match
    defaults: { _controller: CustomWebBundle:JsonKnowledges:match }

json_knowledges_query:
    pattern:  /json/Knowledges/query
    defaults: { _controller: CustomWebBundle:JsonKnowledges:query }

ajax_categories_search:
    pattern:  /ajax/categories/search
    defaults: { _controller: CustomWebBundle:AajxCategories:search }

ajax_categories_match:
    pattern:  /ajax/categories/match
    defaults: { _controller: CustomWebBundle:AajxCategories:match }

ajax_categories_query:
    pattern:  /ajax/categories/query
    defaults: { _controller: CustomWebBundle:AajxCategories:query }

ajax_category_isSubject:
    pattern:  /ajax/categories/check
    defaults: { _controller: CustomWebBundle:AajxCategories:isSubjct }

ajax_questions_count:
    pattern:  /ajax/category/{categoryId}/questions/count
    defaults: { _controller: CustomWebBundle:AjaxQuestion:getQuestionsCount }

course_manage_lesson_create:
    pattern:  /course/{id}/manage/lesson/create
    defaults: { _controller: CustomWebBundle:CourseLessonManage:create }

course_manage_lesson_edit:
    pattern:  /course/{courseId}/manage/lesson/{lessonId}/edit
    defaults: { _controller: CustomWebBundle:CourseLessonManage:edit }

json_courseware_search:
    pattern:  /json/courseware/search
    defaults: { _controller: CustomWebBundle:JsonCourseware:search }

json_essay_search:
    pattern: /json/essay/search
    defaults: { _controller: CustomWebBundle:JsonEssay:search }

json_testpaper_search:
    pattern: /json/testpaper/search
    defaults: { _controller: CustomWebBundle:JsonTestpaper:search }

course_manage_lesson_edit_testpaper:
    pattern:  /course/{courseId}/manage/lesson/{lessonId}/edit/testpaper
    defaults: { _controller: CustomWebBundle:CourseLessonManage:editTestpaper }

course_manage_init_rating:
    pattern:  /course/{id}/manage/init/rating
    defaults: { _controller: CustomWebBundle:CourseInitManage:index }

course_manage_init_rating_create:
    pattern:  /course/{id}/manage/init/rating/create
    defaults: { _controller: CustomWebBundle:CourseInitManage:create }

course_manage_init_rating_delete:
    pattern:  /course/{courseId}/manage/init/rating/{id}/delete
    defaults: { _controller: CustomWebBundle:CourseInitManage:delete }

course_manage_sub_course:
    pattern:  /course/{id}/manage/subcourse
    defaults: { _controller: CustomWebBundle:SubCourseManage:list }

course_manage_sub_course_add:
    pattern:  /course/{id}/manage/subcourse/add
    defaults: { _controller: CustomWebBundle:SubCourseManage:add }

course_manage_sub_course_delete:
    pattern:  /course/{courseId}/manage/subcourse/{id}/delete
    defaults: { _controller: CustomWebBundle:SubCourseManage:delete }

course_manage_sub_course_sort:
    pattern:  /course/{courseId}/manage/subcourse/sort
    defaults: { _controller: CustomWebBundle:SubCourseManage:sort }
    methods: [POST]

course_manage_lecture_note:
    pattern:  /course/{courseId}/manage/lecture-note
    defaults: { _controller: CustomWebBundle:LectureNote:index }

course_manage_lecture_note_create:
    pattern:  /course/{courseId}/lecture-note/create
    defaults: { _controller: CustomWebBundle:LectureNote:create }

course_manage_lecture_note_delete:
    pattern:  /course/lecture-note/{id}/delete
    defaults: { _controller: CustomWebBundle:LectureNote:delete }

courseware_exercise_add:
    pattern:  /course/{courseId}/lesson/{lessonId}/courseware/exercise/add
    defaults: { _controller: CustomWebBundle:CoursewareExercise:add }

course_lesson_learn_show:
    pattern:  /course/lesson/{lessonId}/learn/show
    defaults: { _controller: CustomWebBundle:Lesson:learnShow }

ccviedo_show:
    pattern:  /course/{courseId}/lesson/ccviedo/show
    defaults: { _controller: CustomWebBundle:CCViedoManage:show }

ccviedo_question_preview:
    pattern:  /course/lesson/ccviedo/question/preview
    defaults: { _controller: CustomWebBundle:CCViedoManage:questionPreview }

ccviedo_question_answer_check:
    pattern:  /course/lesson/ccviedo/question/{questionId}/answer/check
    defaults: { _controller: CustomWebBundle:CCViedoManage:answerCheck }

carts_list:
    pattern:  /carts/list
    defaults: { _controller: CustomWebBundle:Carts:list }

carts_delete:
    pattern:  /carts/delete
    defaults: { _controller: CustomWebBundle:Carts:delete }

carts_show:
    pattern:  /carts/show
    defaults: { _controller: CustomWebBundle:Carts:show }

hot_sale_courses:
    pattern:  /hot/sale/courses/index
    defaults: { _controller: CustomWebBundle:Carts:index }

carts_course_favorite:
    pattern: /carts/favourite
    defaults: { _controller: CustomWebBundle:Carts:favorite }