order_create:
    pattern:  /order/create
    defaults: { _controller: CustomWebBundle:CustomOrder:create }
    methods: [POST]

order_show:
    pattern:  /order/show
    defaults: { _controller: CustomWebBundle:CustomOrder:show }

coupon_check:
    pattern:  /{type}/{id}/coupon/check
    defaults: { _controller: CustomWebBundle:CustomOrder:couponCheck }

group:
    pattern:  /group
    defaults: { _controller: CustomWebBundle:CustomGroup:customIndex }
group_show:
    pattern:  /group/{id}
    defaults: { _controller: CustomWebBundle:CustomGroup:groupIndex }

group_sign:
    pattern:  /sign/{groupId}
    defaults: { _controller: CustomWebBundle:Sign:sign }

signed_records:
    pattern:  /sign/{groupId}/records
    defaults: { _controller: CustomWebBundle:Sign:getSignedRecordsByPeriod }

sign_repair:
    pattern:  /sign/{groupId}/repair
    defaults: { _controller: CustomWebBundle:Sign:signRepair }

my_coin:
     path:  /my/coin
     defaults: { _controller: CustomWebBundle:CoinWeb:index }

my_changetest:
    path:  /my/changetest/{startnum}
    defaults: {_controller: CustomWebBundle:ChangeTestWeb:index }