homepage:
    pattern:  /
    defaults: { _controller: CustomWebBundle:Default:index }


settings:
    pattern:  /settings/
    defaults: { _controller: CustomWebBundle:Settings:profile }
    
teacher_tag_match:
    pattern: /teacher/tag/match_jsonp
    defaults: { _controller: CustomWebBundle:TagTeacher:match }
teacher_search:
    pattern: /teacher/search
    defaults: { _controller: CustomWebBundle:Teacher:search }

group:
    pattern:  /group
    defaults: { _controller: CustomWebBundle:Group:index }

course_explore:
    pattern:  /explore/{category}
    defaults: { _controller: CustomWebBundle:Course:explore, category:'' }

guide:
    path:    /guide
    defaults: { _controller: CustomWebBundle:Default:guide }

