admin_user_import:
    pattern:  /user/import/
    defaults: { _controller: TopxiaAdminBundle:UserImporter:importUserInfoByExcel }

admin_user_import_to_base:
    pattern:  /user/import/to/base
    defaults: { _controller: TopxiaAdminBundle:UserImporter:importUserDataToBase }

admin_userImport:
    pattern:  /userimporter/index
    defaults: { _controller: TopxiaAdminBundle:UserImporter:index }

admin_school_teacher_name:
    pattern:  /school/teachers
    defaults: { _controller: TopxiaAdminBundle:School:teacherName }
    methods: [GET]

admin_school_setting:
    pattern:  /school/setting
    defaults: { _controller: TopxiaAdminBundle:School:schoolSetting }

admin_school_classes_setting:
    pattern:  /school/classes/setting
    defaults: { _controller: TopxiaAdminBundle:School:classSetting }

admin_school_homepage_upload:
    pattern:  /school/homepage/upload
    defaults: { _controller: TopxiaAdminBundle:School:homePageUpload }

admin_school_homepage_remove:
    pattern:  /school/homepage/remove
    defaults: { _controller: TopxiaAdminBundle:School:homePageRemove }

admin_school_class_create:
    pattern:  /school/class/create
    defaults: { _controller: TopxiaAdminBundle:School:classCreate }

admin_school_class_edit:
    pattern:  /school/class/{classId}/edit
    defaults: { _controller: TopxiaAdminBundle:School:classEdit }

admin_school_class_delete:
    pattern:  /school/class/delete/{classId}
    defaults: { _controller: TopxiaAdminBundle:School:classDelete }

admin_school_class_course_manage:
    pattern:  /school/class/{classId}/course/manage
    defaults: { _controller: TopxiaAdminBundle:School:classCourseManage }

admin_school_class_member_manage:
    pattern:  /school/class/{classId}/member/manage
    defaults: { _controller: TopxiaAdminBundle:School:classMemberManage }

admin_school_class_course_add:
    pattern:  /school/class/{classId}/course/add
    defaults: { _controller: TopxiaAdminBundle:School:classCourseAdd }

admin_school_class_course_remove:
    pattern:  /school/class/{classId}/course/{courseId}/remove
    defaults: { _controller: TopxiaAdminBundle:School:classCourseRemove }

admin_school_class_icon_upload:
    pattern:  /school/classes/icon/upload
    defaults: { _controller: TopxiaAdminBundle:School:classIconUpload }

admin_school_class_backgroundImg_upload:
    pattern:  /school/classes/backgroundImg/upload
    defaults: { _controller: TopxiaAdminBundle:School:classBackgroundImgUpload }