parameters:

  theme_jianmo_name: "简墨"

  theme_jianmo_default:
    maincolor: default
    navigationcolor: default
    blocks:
      left:
        - title: ""
          count: "12"
          orderBy: "latest"
          categoryId: "all"
          code: course-grid-with-condition-index
          categoryCount: "4"
          defaultTitle: "网校课程"
          id: "latestCourse"
        - title: ""
          count: "4"
          categoryId: ""
          code: "live-course"
          defaultTitle: "近期直播"
          id: "RecentLiveCourses"
        - title: ""
          count: ""
          code: "middle-banner"
          defaultTitle: "中部banner"
          id: "middle-banner"
        - title: ""
          count: "4"
          code: "recommend-classroom"
          defaultTitle: "推荐班级"
          id: "RecommendClassrooms"
        - title: ""
          count: "6"
          code: "groups"
          defaultTitle: "小组动态"
          id: "hotGroups"
        - title: ""
          count: "4"
          categoryId: ""
          code: "recommend-teacher"
          defaultTitle: "推荐教师"
          id: "RecommendTeachers"
    bottom: simple

  theme_jianmo_all:
    maincolor: default
    navigationcolor: default
    blocks:
      left:
        - title: ""
          count: "12"
          orderBy: "latest"
          categoryId: "all"
          code: course-grid-with-condition-index
          defaultTitle: "网校课程"
          id: latestCourse
        - title: ""
          count: "4"
          categoryId: ""
          code: "live-course"
          defaultTitle: "近期直播"
          id: "RecentLiveCourses"
        - title: ""
          count: ""
          code: "middle-banner"
          defaultTitle: "中部banner"
          id: "middle-banner"
        - title: ""
          count: "6"
          code: "groups"
          defaultTitle: "小组动态"
          id: "hotGroups"
        - title: ""
          count: "3"
          categoryId: ""
          code: "recommend-teacher"
          defaultTitle: "推荐教师"
          id: "RecommendTeachers"
    bottom: simple
services:
#    topxia_admin.example:
#        class: %topxia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
