admin_coupon:
    pattern: /coupon
    defaults: { _controller: CouponBundle:CouponBatch:index }

admin_coupon_generate:
    pattern: /coupon/generate
    defaults: { _controller: CouponBundle:CouponBatch:generate }

admin_coupon_checkprefix:
    pattern: /coupon/checkprefix
    defaults: { _controller: CouponBundle:CouponBatch:checkPrefix }

admin_coupon_delete:
    pattern: /coupon/{id}/delete
    defaults: { _controller: CouponBundle:CouponBatch:delete }
    methods: [POST]

admin_coupon_query:
    pattern: /coupon/index
    defaults: { _controller: CouponBundle:Coupon:index }

admin_coupon_batch_export:
    pattern: /coupon/export/csv/{batchId}
    defaults: { _controller: CouponBundle:CouponBatch:exportCsv }

admin_coupon_show:
    pattern: /coupon/show/{batchId}
    defaults: { _controller: CouponBundle:CouponBatch:detail }