parameters:
#    coupon.example.class: Coupon\CouponBundle\Example

services:
#    coupon.example:
#        class: %coupon.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
