admin_vip_create:
    pattern: /vip/create
    defaults: { _controller: VipBundle:VipAdmin:create }

admin_vip_order:
    pattern: /vip/order
    defaults: { _controller: VipBundle:VipAdmin:order }

admin_vip_cancel:
    pattern: /vip/user/{userId}/cancel
    defaults: { _controller: VipBundle:VipAdmin:cancel }

admin_vip_list:
    pattern: /vip/type/{type}
    defaults: { _controller: VipBundle:VipAdmin:index, type: 'all' }

admin_vip_update:
    pattern: /vip/update
    defaults: { _controller: VipBundle:VipAdmin:update }

admin_vip_bought_history:
    pattern: /vip/bought/history
    defaults: { _controller: VipBundle:VipAdmin:boughtHistory}

admin_vip_bought_list:
    pattern: /vip/bought/list
    defaults: { _controller: VipBundle:VipAdmin:boughtList}

admin_vip_edit:
    pattern: /vip/user/{userId}/edit
    defaults: { _controller: VipBundle:VipAdmin:edit}

admin_vip_create_nickname_check:
    pattern:  /vip/create/nickname/check
    defaults: { _controller: VipBundle:VipAdmin:nicknameCheck }

admin_vip_level:
    pattern: /vip/level
    defaults: { _controller: VipBundle:VipLevelAdmin:index }

admin_vip_level_create:
    pattern: /vip/level/create
    defaults: { _controller: VipBundle:VipLevelAdmin:create }

admin_vip_level_update:
    pattern: /vip/level/{id}/update
    defaults: { _controller: VipBundle:VipLevelAdmin:update }

admin_vip_level_delete:
    pattern: /vip/level/{id}/delete
    defaults: { _controller: VipBundle:VipLevelAdmin:delete }
    methods: [POST]

admin_vip_level_sort:
    pattern: /vip/level/sort
    defaults: { _controller: VipBundle:VipLevelAdmin:sort }

admin_vip_level_picture:
    pattern: /vip/level/picture
    defaults: { _controller: VipBundle:VipLevelAdmin:picture }

admin_vip_level_icon:
    pattern: /vip/level/icon
    defaults: { _controller: VipBundle:VipLevelAdmin:icon }

admin_vip_level_on:
    pattern: /vip/level/{id}/on
    defaults: { _controller: VipBundle:VipLevelAdmin:on }

admin_vip_level_off:
    pattern: /vip/level/{id}/off
    defaults: { _controller: VipBundle:VipLevelAdmin:off }

admin_level_setting:
    pattern: /vip/level/setting
    defaults: { _controller: VipBundle:VipLevelAdmin:zone }

