#question
course_set_manage_question:
    path: /course_set/{id}/manage/question
    defaults: { _controller: AppBundle:QuestionManage:index }

course_set_manage_question_create:
    path: /course_set/{id}/manage/question/{type}/create
    defaults: { _controller: AppBundle:QuestionManage:create }

course_set_manage_question_update:
    path: /course_set/{courseSetId}/manage/question/{questionId}/update
    defaults: { _controller: AppBundle:QuestionManage:update }

course_set_manage_question_delete:
    path: /course_set/{courseSetId}/manage/question/delete/{questionId}
    defaults: { _controller: AppBundle:QuestionManage:delete }
    methods: [POST]

course_set_manage_question_deletes:
    path: /course_set/{courseSetId}/manage/question/deletes
    defaults: { _controller: AppBundle:QuestionManage:deletes }
    methods: [POST]

course_set_manage_question_preview:
    path: /course_set/{courseSetId}/manage/question/{questionId}/preview
    defaults: { _controller: AppBundle:QuestionManage:preview }

course_set_manage_question_picker:
  path: /course_set/{courseId}/manage/question/picker
  defaults: { _controller: AppBundle:QuestionManage:questionPicker }

course_set_manage_question_picked:
  path:  /course_set/{courseId}/manage/question/{questionId}/picked
  defaults: { _controller: AppBundle:QuestionManage:pickedQuestion }

course_set_manage_question_check:
  path: /course_set/{id}/manage/question/check
  defaults: { _controller: AppBundle:QuestionManage:check }
