services:
    extension.manager:
        class: AppBundle\Extension\ExtensionManager

    extension.default:
        class: AppBundle\Extension\DefaultExtension
        tags:
            - { name: extension }

    biz.service_provider.collector:
        class: Biz\ServiceProviderCollector

