services:
    article_article_event_subscriber:
        class: Biz\Article\Event\ArticleEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    card_event_subscriber:
        class: Biz\Card\Event\EventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_message_event_subscriber:
        class: Biz\User\Event\MessageEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_order_event_subscriber:
        class: Biz\User\Event\OrderEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_status_event_subscriber:
        class: Biz\User\Event\StatusEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_user_event_subscriber:
        class: Biz\User\Event\UserEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_vip_member_event_subscriber:
        class: Biz\User\Event\VipMemberEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    task_event_subscriber:
        class: Biz\Task\Event\ActivitySubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    live_activity_event_subscriber:
        class: Biz\Activity\Event\ThreadSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_statistics_event_subscriber:
        class: Biz\Course\Event\StatisticsSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    extension.manager:
        class: AppBundle\Extension\ExtensionManager

    extension.default:
        class: AppBundle\Extension\DefaultExtension
        arguments: ['@biz']
        tags:
            - { name: extension }

    biz.service_provider.collector:
        class: Biz\ServiceProviderCollector

    upload_file_event_subscriber:
        class: Biz\File\Event\UploadFileEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    question_event_subscriber:
        class: Biz\Question\Event\QuestionEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    web.twig.question_type_extension:
        class: AppBundle\Twig\QuestionTypeExtension
        arguments:    ['@service_container','@biz']
        tags:
            - { name: twig.extension }

    web.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@biz']
        tags:
            - { name: twig.extension }

    web.twig.activity_extension:
        class: AppBundle\Twig\ActivityExtension
        arguments:    ['@service_container','@biz']
        tags:
            - { name: twig.extension }
