services:
    article_article_event_subscriber:
        class: Biz\Article\Event\ArticleEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    card_event_subscriber:
        class: Biz\Card\Event\EventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_note_event_subscriber:
        class: Biz\Course\Event\NoteEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_member_event_subscriber:
        class: Biz\Course\Event\CourseMemberEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    content_event_subscriber:
        class: Biz\Content\Event\ContentEventSubscriber
        arguments: ['@biz']
        tags:
           - { name: codeages_plugin.event.subscriber }

    user_course_thread_event_subscriber:
        class: Biz\User\Event\CourseThreadEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_classroom_event_subscriber:
        class: Biz\User\Event\ClassroomEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_user_event_subscriber:
        class: Biz\User\Event\UserEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    user_vip_member_event_subscriber:
        class: Biz\User\Event\VipMemberEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    task_event_subscriber:
        class: Biz\Task\Event\ActivitySubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    taxonomy_article_event_subscriber:
        class: Biz\Taxonomy\Event\ArticleEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }


    activity_event_subscriber:
        class: Biz\Activity\Event\ThreadSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    classroom_event_subscriber:
        class: Biz\Classroom\Event\ClassroomEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_statistics_event_subscriber:
        class: Biz\Course\Event\StatisticsSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_set_statistics_event_subscriber:
        class: Biz\Course\Event\CourseSetStatisticsSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_set_material_event_subscriber:
        class: Biz\Course\Event\CourseSetMaterialEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    conversation_event_subscriber:
        class: Biz\IM\Event\ConversationEventSubscriber
        arguments: ['@biz']
        tags: 
            - { name: codeages_plugin.event.subscriber }

    extension.manager:
        class: AppBundle\Extension\ExtensionManager

    extension.default:
        class: AppBundle\Extension\DefaultExtension
        arguments: ['@biz']
        tags:
            - { name: extension }

    biz.service_provider.collector:
        class: Biz\ServiceProviderCollector

    upload_file_event_subscriber:
        class: Biz\File\Event\UploadFileEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    question_event_subscriber:
        class: Biz\Question\Event\QuestionEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    notification_event_subscriber:
        class: Biz\Notification\Event\PushMessageEventSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    opencourse_event_subscriber:
        class: Biz\OpenCourse\Event\OpenCourseEventSubscriber
        arguments: ['@biz']
        tags:
                - { name: codeages_plugin.event.subscriber }

    orderrefererlog_event_subscriber:
        class: Biz\RefererLog\Event\OrderRefererLogEventSubscriber
        arguments: ['@biz']
        tags:
                - { name: codeages_plugin.event.subscriber }
    tokenbucket_event_subscriber:
        class: Biz\PostFilter\Event\TokenBucketEventSubscriber
        arguments: ['@biz']
        tags:
                - { name: codeages_plugin.event.subscriber }

    web.twig.question_type_extension:
        class: AppBundle\Twig\QuestionTypeExtension
        arguments:    ['@service_container','@biz']
        tags:
            - { name: twig.extension }

    web.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@biz']
        tags:
            - { name: twig.extension }

    web.twig.activity_extension:
        class: AppBundle\Twig\ActivityExtension
        arguments:    ['@service_container','@biz']
        tags:
            - { name: twig.extension }


