course_activities:
  pattern:  /course/{courseId}/activities
  defaults: { _controller: ActivityBundle:ActivityManage:activities }

course_activity_create:
  pattern:  /course/{courseId}/activity/{type}
  defaults: { _controller: ActivityBundle:ActivityManage:create }

course_activity_update:
  pattern:  /course/{courseId}/activity/{id}/update
  defaults: { _controller: ActivityBundle:ActivityManage:update }

course_activity_delete:
  pattern:  /course/{courseId}/activity/{id}/delete
  defaults: { _controller: ActivityBundle:ActivityManage:delete }