admin_periodic_course_add:
    name: 创建周期课程
    parent: admin_course_manage
    router_name: course_create
    router_params: {'flag': 'periodic'}
    group: 2
    blank: 1
    before: admin_course_add

admin_app_center_show:
    name: ES(慕课版)应用
    parent: admin_app
    router_name: admin_app_center
    router_params: { postStatus : all }

admin_operation_organization_manage:
    name: 学校管理
    parent: admin_system
    router_name: admin_organization

admin_operation_organization_create:
    name: 添加学校组织
    parent: admin_operation_organization_manage
    router_name: admin_organization_create
    mode: modal
    group: 2