admin_course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: MoocAdminBundle:RoundCourse:nextRound }

admin_course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: MoocAdminBundle:RoundCourse:rounding }

admin_classroom_create:
    pattern:  /classroom/create
    defaults: { _controller: MoocAdminBundle:ClassroomAdmin:addClassroom }

admin_organization:
    pattern:  /organization
    defaults: { _controller: MoocAdminBundle:Organization:index}

admin_organization_create:
    pattern:  /organization-create
    defaults: { _controller: MoocAdminBundle:Organization:create}

admin_organization_check:
    pattern:  /organization/check/{type}
    defaults: { _controller: MoocAdminBundle:Organization:check}

admin_organization_check_parentId:
    pattern:  /organization/check-parentId
    defaults: { _controller: MoocAdminBundle:Organization:checkParentId}

admin_organization_edit:
    pattern:  /organization/{id}/edit
    defaults: { _controller: MoocAdminBundle:Organization:edit}

admin_organization_delete:
    pattern:  /organization/{id}/delete
    defaults: { _controller: MoocAdminBundle:Organization:delete}