parameters:

  theme_mooc_name: "慕课"

  theme_mooc_default:
    maincolor: default
    navigationcolor: default
    blocks:
      # right:
      #   - title: ""
      #     count: "8"
      #     orderBy: ""
      #     code: "announcement"
      #     defaultTitle: "公告"
      #     id: "announcement"
      left:
        - title: ""
          count: ""
          code: "category"
          defaultTitle: "分类设置"
          id: "category"
        - title: ""
          count: "10"
          orderBy: "latest"
          code: "course-grid-with-condition-index"
          defaultTitle: "学校课程"
          subTitle: ""
          defaultSubTitle: "精选课程，满足你的学习兴趣。"
          id: "latestCourse"
        - title: ""
          count: ""
          code: "middle-banner"
          defaultTitle: "中部banner"
          id: "middle-banner"
        - title: ""
          count: "6"
          code: "latest-classroom"
          defaultTitle: "学校专业"
          subTitle: ""
          defaultSubTitle: "专业化学习体系，给你更多的课程相关服务。"
          id: "latestClassrooms"
        - title: ""
          count: "8"
          categoryId: ""
          code: "recommend-teacher"
          defaultTitle: "名师风采"
          subTitle: ""
          defaultSubTitle: "名师汇集，保证教学质量与学习效果。"
          id: "RecommendTeachers"
        - title: ""
          count: ""
          code: "bottom-partner"
          defaultTitle: "底部合作伙伴"
          id: "bottom-partner"
    bottom: simple

  theme_mooc_all:
    maincolor: default
    navigationcolor: default
    blocks:
      # right:
      #   - title: ""
      #     count: "8"
      #     orderBy: ""
      #     code: "announcement"
      #     defaultTitle: "公告"
      #     id: "announcement"
      left:
        - title: ""
          count: ""
          code: "category"
          defaultTitle: "分类设置"
          id: "category"
        - title: ""
          count: "10"
          orderBy: "latest"
          code: "course-grid-with-condition-index"
          defaultTitle: "学校课程"
          subTitle: ""
          defaultSubTitle: "精选课程，满足你的学习兴趣。"
          id: "latestCourse"
        - title: ""
          count: ""
          code: "middle-banner"
          defaultTitle: "中部banner"
          id: "middle-banner"
        - title: ""
          count: "4"
          code: "latest-classroom"
          defaultTitle: "学校专业"
          subTitle: ""
          defaultSubTitle: "专业化学习体系，给你更多的课程相关服务。"
          id: "latestClassrooms"
        - title: ""
          count: "8"
          categoryId: ""
          code: "recommend-teacher"
          defaultTitle: "名师风采"
          subTitle: ""
          defaultSubTitle: "名师汇集，保证教学质量与学习效果。"
          id: "RecommendTeachers"
        - title: ""
          count: ""
          code: "bottom-partner"
          defaultTitle: "底部合作伙伴"
          id: "bottom-partner"
    bottom: simple
services:
#    topxia_admin.example:
#        class: %topxia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
