course_manage_tasks:
  path:  /course/{courseId}/tasks
  defaults: { _controller: WebBundle:TaskManage:tasks }

course_manage_task_activity_types:
  path:  /course/{courseId}/task/activity_types
  defaults: { _controller: WebBundle:TaskManage:activityTypes}

course_manage_task_create:
  path:  /course/{courseId}/task/create/{type}
  defaults: { _controller: WebBundle:TaskManage:create }

course_manage_task_update:
  path:  /course/{courseId}/task/{id}/update
  defaults: { _controller: WebBundle:TaskManage:update }

course_manage_task_delete:
  path:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: WebBundle:TaskManage:delete }

course_task_show:
  path:  /course/{courseId}/task/{id}/show
  defaults: { _controller: WebBundle:Task:show }

course_task_activity_show:
  path:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: WebBundle:Task:taskActivity }

course_task_trigger:
  path:  /course/{courseId}/task/{id}/trigger/{eventName}
  defaults: { _controller: WebBundle:Task:trigger }
  methods: [POST]