courseset_manage:
  path: /courseset/{id}
  defaults: {_controller: WebBundle:CourseSetManage:index}

courseset_manage_courses:
  path: /courseset/{courseSetId}/courses
  defaults: {_controller:WebBundle:CourseManage:list}

courseset_manage_course_create:
  path: /courseset/{courseSetId}/course/create
  defaults: {_controller: WebBundle:CourseManage:create}

courseset_manage_course_copy:
  path: /courseset/{courseSetId}/course/{courseId}/copy
  defaults: {_controller: WebBundle:CourseManage:copy}

courseset_manage_course_info:
  path: /courseset/{courseSetId}/course/{courseId}/info
  defaults: {_controller: WebBundle:CourseManage:info}

courseset_manage_course_tasks:
  path: /courseset/{courseSetId}/course/{courseId}/tasks
  defaults: {_controller: WebBundle:CourseManage:tasks}


courseset_manage_course_marketing:
  path: /courseset/{courseSetId}/course/{courseId}/marketing
  defaults: {_controller: WebBundle:CourseManage:marketing}

courseset_manage_course_preview:
  path: /courseset/{courseSetId}/course/{courseId}/preview
  defaults: {_controller: WebBundle:CourseManage:preview}

courseset_manage_course_teachers:
  path: /courseset/{courseSetId}/course/{courseId}/teachers
  defaults: {_controller: WebBundle:CourseManage:teachers}

courseset_manage_course_students:
  path: /courseset/{courseSetId}/course/{courseId}/students
  defaults: {_controller: WebBundle:CourseManage:students}

courseset_manage_course_close:
  path: /courseset/{courseSetId}/course/{courseId}/close
  defaults: {_controller: WebBundle:CourseManage:close}

courseset_manage_course_delete:
  path: /courseset/{courseSetId}/course/{courseId}/delete
  defaults: {_controller: WebBundle:CourseManage:delete}

courseset_manage_course_publish:  
  path: /courseset/{courseSetId}/course/{courseId}/publish
  defaults: {_controller: WebBundle:CourseManage:publish}

course_manage_tasks:
  path:  /course/{courseId}/tasks
  defaults: { _controller: WebBundle:TaskManage:tasks }

course_manage_task_create:
  path:  /course/{courseId}/task
  defaults: { _controller: WebBundle:TaskManage:create}

course_manage_task_fields:
  path:  /course/{courseId}/task_fields/{mode}
  defaults: { _controller: WebBundle:TaskManage:taskFields }

course_manage_task_update:
  path:  /course/{courseId}/task/{id}/update
  defaults: { _controller: WebBundle:TaskManage:update }

course_manage_task_delete:
  path:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: WebBundle:TaskManage:delete }

course_task_show:
  path:  /course/{courseId}/task/{id}/show
  defaults: { _controller: WebBundle:Task:show }

course_task_activity_show:
  path:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: WebBundle:Task:taskActivity }

task_live_entry:
  path: /course/{courseId}/activity/{id}/live_entry
  defaults: {_controller: WebBundle:LiveActivity:liveEntry}

course_activity_trigger:
  path: /course/{courseId}/activity/{activityId}/trigger
  defaults: { _controller: WebBundle:Activity:trigger }
  methods: [POST]

media_materiallib_choose:
    path: /media/materiallib/choose
    defaults: { _controller: WebBundle:FileChooser:materialChoose }

media_materiallib_contacts:
    path: /media/materiallib/contacts
    defaults: { _controller: WebBundle:FileChooser:findMySharingContacts }

media_corusefile_choose:
    path: /media/corusefile/{courseId}/choose
    defaults: { _controller: WebBundle:FileChooser:CourseFileChoose }

media_video_import:
    path: /media/course/{courseId}/import
    defaults: { _controller: WebBundle:FileChooser:import }

uploader_auth_v2:
    path:  /uploader/v2/auth
    defaults: { _controller: WebBundle:Uploader:auth }
    methods: [GET]

uploader_init_v2:
  path:  /uploader/v2/init
  defaults: { _controller: WebBundle:Uploader:init }
  methods: [GET]

uploader_finished_v2:
  path:  /uploader/v2/finished
  defaults: { _controller: WebBundle:Uploader:finished }
  methods: [GET]
