course_manage_tasks:
  path:  /course/{courseId}/tasks
  defaults: { _controller: WebBundle:TaskManage:tasks }

course_manage_task_create:
  path:  /course/{courseId}/task
  defaults: { _controller: WebBundle:TaskManage:create}

course_manage_task_fields:
  path:  /course/{courseId}/task_fields/{mode}
  defaults: { _controller: WebBundle:TaskManage:taskFields }

course_manage_task_update:
  path:  /course/{courseId}/task/{id}/update
  defaults: { _controller: WebBundle:TaskManage:update }

course_manage_task_delete:
  path:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: WebBundle:TaskManage:delete }

course_task_show:
  path:  /course/{courseId}/task/{id}/show
  defaults: { _controller: WebBundle:Task:show }

course_task_activity_show:
  path:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: WebBundle:Task:taskActivity }
task_live_entry:
  path: /course/{courseId}/activity/{id}/live_entry
  defaults: {_controller: WebBundle:LiveActivity:liveEntry}
course_task_trigger:
  path:  /course/{courseId}/task/{id}/trigger/{eventName}
  defaults: { _controller: WebBundle:Task:trigger }
  methods: [POST]

media_materiallib_choose:
    path: /media/materiallib/choose
    defaults: { _controller: WebBundle:MediaProccess:materialChoose }

media_materiallib_contacts:
    path: /media/materiallib/contacts
    defaults: { _controller: WebBundle:MediaProccess:findMySharingContacts }

media_corusefile_choose:
    path: /media/corusefile/{courseId}/choose
    defaults: { _controller: WebBundle:MediaProccess:CourseFileChoose }

media_video_import:
    path: /media/course/{courseId}/import
    defaults: { _controller: WebBundle:MediaProccess:import }


uploader_init_v2:
  path:  /uploader/v2/init
  defaults: { _controller: WebBundle:Uploader:init }
  methods: [GET]

uploader_finished_v2:
  path:  /uploader/v2/finished
  defaults: { _controller: WebBundle:Uploader:finished }
  methods: [GET]
