course_manage_tasks:
  path:  /course/{courseId}/tasks
  defaults: { _controller: WebBundle:TaskManage:tasks }

course_manage_task_create:
  path:  /course/{courseId}/task
  defaults: { _controller: WebBundle:TaskManage:create}

course_manage_task_fields:
  path:  /course/{courseId}/task_fields/{mode}
  defaults: { _controller: WebBundle:TaskManage:taskFields }

course_manage_task_update:
  path:  /course/{courseId}/task/{id}/update
  defaults: { _controller: WebBundle:TaskManage:update }

course_manage_task_delete:
  path:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: WebBundle:TaskManage:delete }

course_task_show:
  path:  /course/{courseId}/task/{id}/show
  defaults: { _controller: WebBundle:Task:show }

course_task_activity_show:
  path:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: WebBundle:Task:taskActivity }
task_live_entry:
  path: /course/{courseId}/activity/{id}/live_entry
  defaults: {_controller: WebBundle:LiveActivity:liveEntry}
course_task_trigger:
  path:  /course/{courseId}/task/{id}/trigger/{eventName}
  defaults: { _controller: WebBundle:Task:trigger }
  methods: [POST]

media_materiallib_choose:
    path: /media/materiallib/choose
    defaults: { _controller: WebBundle:FileChooser:materialChoose }

media_materiallib_contacts:
    path: /media/materiallib/contacts
    defaults: { _controller: WebBundle:FileChooser:findMySharingContacts }

media_corusefile_choose:
    path: /media/corusefile/{courseId}/choose
    defaults: { _controller: WebBundle:FileChooser:CourseFileChoose }

media_video_import:
    path: /media/course/{courseId}/import
    defaults: { _controller: WebBundle:FileChooser:import }

uploader_auth_v2:
    path:  /uploader/v2/auth
    defaults: { _controller: WebBundle:Uploader:auth }
    methods: [GET]

uploader_init_v2:
  path:  /uploader/v2/init
  defaults: { _controller: WebBundle:Uploader:init }
  methods: [GET]

uploader_finished_v2:
  path:  /uploader/v2/finished
  defaults: { _controller: WebBundle:Uploader:finished }
  methods: [GET]

#question
course_manage_question:
    path: /course/{courseId}/manage/question
    defaults: { _controller: WebBundle:QuestionManage:index }

course_manage_question_create:
    path: /course/{courseId}/manage/question/{type}/create
    defaults: { _controller: WebBundle:QuestionManage:create }

course_manage_question_update:
    path: /course/{courseId}/manage/question/{id}/update
    defaults: { _controller: WebBundle:QuestionManage:update }

course_manage_question_delete:
    path: /course/{courseId}/manage/question/delete/{id}
    defaults: { _controller: WebBundle:QuestionManage:delete }
    methods: [POST]

course_manage_question_deletes:
    path: /course/{courseId}/manage/question/deletes
    defaults: { _controller: WebBundle:QuestionManage:deletes }
    methods: [POST]

course_manage_question_preview:
    path: /course/{courseId}/manage/question/{id}/preview
    defaults: { _controller: WebBundle:QuestionManage:preview }

course_manage_question_picker:
  path: /course/{courseId}/manage/question/picker
  defaults: { _controller: WebBundle:QuestionManage:questionPicker }

course_manage_question_picked:
  path:  /course/{courseId}/manage/question/{questionId}/picked
  defaults: { _controller: WebBundle:QuestionManage:PickedQuestion }


#testpaper
course_manage_testpaper:
  path: /course/{courseId}/manage/testpaper
  defaults: { _controller: WebBundle:TestpaperManage:index }

course_manage_testpaper_create:
  path: /course/{courseId}/manage/testpaper/create
  defaults: { _controller: WebBundle:TestpaperManage:create }

course_manage_testpaper_publish:
    path: /course/{courseId}/manage/testpaper/{id}/publish
    defaults: { _controller: WebBundle:TestpaperManage:publish }

course_manage_testpaper_close:
    path: /course/{courseId}/manage/testpaper/{id}/close
    defaults: { _controller: WebBundle:TestpaperManage:close }

course_manage_testpaper_questions:
  path: /course/{courseId}/manage/testpaper/{testpaperId}/items
  defaults: { _controller: WebBundle:TestpaperManage:questions }

course_manage_testpaper_items_get:
  path: /course/{courseId}/manage/testpaper/items/get
  defaults: { _controller: WebBundle:TestpaperManage:itemsGet }

testpaper_do:
  path: /lesson/{lessonId}/testpaper/{testId}/do
  defaults: { _controller: WebBundle:Testpaper:doTestpaper }

testpaper_show:
  path: /testpaper/{resultId}/show
  defaults: { _controller: WebBundle:Testpaper:doTest }

testpaper_result_show:
  path: /testpaper/result/{resultId}/show
  defaults: { _controller: WebBundle:Testpaper:showResult }

testpaper_result_submit:
  path: /testpaper/result/{resultId}/submit
  defaults: { _controller: WebBundle:Testpaper:submitTest }
  methods: [POST]

testpaper_finish:
  path: /testpaper/result/{resultId}/finish
  defaults: { _controller: WebBundle:Testpaper:finishTest }


#homework
course_manage_homework:
  path: /course/{courseId}/manage/homework
  defaults: { _controller: WebBundle:HomeworkManage:index }

course_manage_homework_create:
  path: /course/{courseId}/manage/lesson/{lessonId}/homework/create
  defaults: { _controller: WebBundle:HomeworkManage:create }

course_manage_homework_question_picked:
  path: /course/{courseId}/manage/question/picked
  defaults: { _controller: WebBundle:HomeworkManage:questionPicked }

homework_start_do:
    pattern: /homework/{homeworkId}/startDo
    defaults: { _controller: WebBundle:Homework:startDo }

homework_show:
    pattern: /homework/{resultId}/show
    defaults: { _controller: WebBundle:Homework:doTest }

homework_result_show:
    pattern: /homework/result/{resultId}/show
    defaults: { _controller: WebBundle:Homework:showResult }



#exercise
course_manage_exercise_create:
  path: /course/{courseId}/manage/lesson/{lessonId}/exercise/create
  defaults: { _controller: WebBundle:ExerciseManage:create }

#todo 与homework_check合并
course_manage_exercise_check:
  path:  /course/{courseId}/manage/exercise/check
  defaults: { _controller: WebBundle:ExerciseManage:buildCheck }

exercise_start_do:
    pattern: /exercise/{exerciseId}/startDo
    defaults: { _controller: WebBundle:Exercise:startDo }

exercise_show:
    pattern: /exercise/{resultId}/show
    defaults: { _controller: WebBundle:Exercise:doTest }

exercise_result_show:
    pattern: /exercise/result/{resultId}/show
    defaults: { _controller: WebBundle:Exercise:showResult }





