course_set_manage_create:
  path: /course_set/create
  defaults: {_controller: WebBundle:CourseSetManage:create}

course_set_show:
  path: /course_set/{id}
  defaults: {_controller: WebBundle:CourseSet:show}

course_set_preview:
  path: /course_set/{id}/preview
  defaults: {_controller: WebBundle:CourseSet:preview}

course_set_manage:
  path: /course_set/{id}/manage
  defaults: {_controller: WebBundle:CourseSetManage:index}

course_set_manage_base:
  path: /course_set/{id}/manage/base
  defaults: {_controller: WebBundle:CourseSetManage:base}

course_set_manage_detail:
  path: /course_set/{id}/manage/detail
  defaults: {_controller: WebBundle:CourseSetManage:detail}

course_set_manage_cover:
  path: /course_set/{id}/manage/cover
  defaults: {_controller: WebBundle:CourseSetManage:cover}

course_set_manage_courses:
  path: /course_set/{courseSetId}/manage/courses
  defaults: {_controller:WebBundle:CourseManage:list}

course_set_manage_course_create:
  path: /course_set/{courseSetId}/manage/course/create
  defaults: {_controller: WebBundle:CourseManage:create}

course_set_manage_course_info:
  path: /course_set/{courseSetId}/manage/course/{courseId}/info
  defaults: {_controller: WebBundle:CourseManage:info}

course_set_manage_course_tasks:
  path: /course_set/{courseSetId}/manage/course/{courseId}/tasks
  defaults: {_controller: WebBundle:CourseManage:tasks}

course_set_manage_course_marketing:
  path: /course_set/{courseSetId}/manage/course/{courseId}/marketing
  defaults: {_controller: WebBundle:CourseManage:marketing}

course_set_manage_course_close:
  path: /course_set/{courseSetId}/course/{courseId}/close
  defaults: {_controller: WebBundle:CourseManage:close}

course_set_manage_course_delete:
  path: /course_set/{courseSetId}/course/{courseId}/delete
  defaults: {_controller: WebBundle:CourseManage:delete}

course_set_manage_course_publish:  
  path: /course_set/{courseSetId}/course/{courseId}/publish
  defaults: {_controller: WebBundle:CourseManage:publish}

course_manage_tasks:
  path:  /course/{courseId}/manage/tasks
  defaults: { _controller: WebBundle:CourseManage:tasks }

course_manage_items_sort:
  path:  /course/{courseId}/manage/items/sort
  defaults: { _controller: WebBundle:CourseManage:courseItemsSort }
  methods: ['POST']

course_manage_chapter_create:
    path:  /course/{id}/manage/chapter/create
    defaults: { _controller: WebBundle:CourseChapterManage:create }

course_manage_chapter_edit:
    path:  /course/{courseId}/manage/chapter/{chapterId}/edit
    defaults: { _controller: WebBundle:CourseChapterManage:edit }

course_manage_chapter_delete:
    path:  /course/{courseId}/manage/chapter/{chapterId}/delete
    defaults: { _controller: WebBundle:CourseChapterManage:delete }
    methods: [POST]

course_manage_task_create:
  path:  /course/{courseId}/task
  defaults: { _controller: WebBundle:TaskManage:create}

course_manage_task_fields:
  path:  /course/{courseId}/task_fields/{mode}
  defaults: { _controller: WebBundle:TaskManage:taskFields }

course_manage_task_update:
  path:  /course/{courseId}/task/{id}/update
  defaults: { _controller: WebBundle:TaskManage:update }

course_manage_task_delete:
  path:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: WebBundle:TaskManage:delete }

course_task_show:
  path:  /course/{courseId}/task/{id}/show
  defaults: { _controller: WebBundle:Task:show }

course_activity_download:
    path: /course/{courseId}/activiy/{activityId}/download
    defaults: { _controller: WebBundle:DownLoadActivity:downloadFile }

course_task_activity_show:
  path:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: WebBundle:Task:taskActivity }

task_live_entry:
  path: /course/{courseId}/activity/{id}/live_entry
  defaults: {_controller: WebBundle:LiveActivity:liveEntry}

course_activity_trigger:
  path: /course/{courseId}/activity/{activityId}/trigger
  defaults: { _controller: WebBundle:Activity:trigger }
  methods: [POST]

media_materiallib_choose:
    path: /media/materiallib/choose
    defaults: { _controller: WebBundle:FileChooser:materialChoose }

media_materiallib_contacts:
    path: /media/materiallib/contacts
    defaults: { _controller: WebBundle:FileChooser:findMySharingContacts }

media_course_file_choose:
    path: /media/corusefile/{courseId}/choose
    defaults: { _controller: WebBundle:FileChooser:courseFileChoose }

media_video_import:
    path: /media/course/{courseId}/import
    defaults: { _controller: WebBundle:FileChooser:import }

uploader_auth_v2:
    path:  /uploader/v2/auth
    defaults: { _controller: WebBundle:Uploader:auth }
    methods: [GET]

uploader_init_v2:
  path:  /uploader/v2/init
  defaults: { _controller: WebBundle:Uploader:init }
  methods: [GET]

uploader_finished_v2:
  path:  /uploader/v2/finished
  defaults: { _controller: WebBundle:Uploader:finished }
  methods: [GET]
