parameters:

services:
    task_event_subscriber:
        class: Biz\Task\Event\ActivitySubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    web.twig.activity_extension:
        class: WebBundle\Twig\ActivityExtension
        arguments:    ['@biz']
        tags:
            - { name: twig.extension }