parameters:

services:
    task_event_subscriber:
        class: Biz\Task\Event\ActivitySubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }
            
    live_activity_event_subscriber:
        class: Biz\LiveActivity\Event\ThreadSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    course_statistics_event_subscriber:     
        class: Biz\Course\Event\StatisticsSubscriber
        arguments: ['@biz']
        tags:
            - { name: codeages_plugin.event.subscriber }

    web.twig.app_extension:
        class: WebBundle\Twig\AppExtension
        arguments: ['@biz'] 
        tags: 
            - { name: twig.extension }
    
